//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Pages {
    
    
    public partial class _300_SeihoBunshoSakusei_YoukiHousou_Tab {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Tos.Web.SiteMaster Master {
            get {
                return ((Tos.Web.SiteMaster)(base.Master));
            }
        }
    }
}
