//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_SVF {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_SVF() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tos.Web.Properties.Resource.SVF", typeof(Resource_SVF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   調整値の書き込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AdjustmentErrorMessage {
            get {
                return ResourceManager.GetString("AdjustmentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更内容に誤りがあります（属性変更）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AttributeChangeErrorMessage {
            get {
                return ResourceManager.GetString("AttributeChangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当するフィールド名がありません（属性変更） 。指定した属性変更は無視されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AttributeFieldExistsErrorMessage {
            get {
                return ResourceManager.GetString("AttributeFieldExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当する項目名がありません（属性変更）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AttributeInvalidErrorMessage {
            get {
                return ResourceManager.GetString("AttributeInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB 接続エラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DBConnectionErrorMessage {
            get {
                return ResourceManager.GetString("DBConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィールド数が不足しています。出力されたデータは無視されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FieldCountErrorMessage {
            get {
                return ResourceManager.GetString("FieldCountErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正フィールド名が指定されています。出力されたデータは無視されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FieldNameErrorMessage {
            get {
                return ResourceManager.GetString("FieldNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単体項目に対して項目番号を指定した、または配列項目に対する項目番号が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormModeCountErrorMessage {
            get {
                return ResourceManager.GetString("FormModeCountErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィールド名が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormModeFieldErrorMessage {
            get {
                return ResourceManager.GetString("FormModeFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グラフィックモードに対応していない制御コードを使用しているにも関わらず、グラフィックモードでのみ有効なオブジェクトが設計されている様式ファイルを使用しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GraphicErrorMessage {
            get {
                return ResourceManager.GetString("GraphicErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イメージファイルのオープンエラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageFileErrorMessage {
            get {
                return ResourceManager.GetString("ImageFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソートインデックスの作成エラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IndexErrorMessage {
            get {
                return ResourceManager.GetString("IndexErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メソッドの引数に誤りがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidErrorMessage {
            get {
                return ResourceManager.GetString("InvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JavaVM内に不正な処理がありました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JavaVMErrorMessage {
            get {
                return ResourceManager.GetString("JavaVMErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   様式ファイルが読み込まれていないのにデータが出力されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutErrorMessage {
            get {
                return ResourceManager.GetString("LayoutErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書式ファイルの読み込みエラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutExistsErrorMessage {
            get {
                return ResourceManager.GetString("LayoutExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   様式ファイルが読み込まれていないのに実行しようとしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutQueryErrorMessage {
            get {
                return ResourceManager.GetString("LayoutQueryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用不可能なメソッドが利用されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotSupportedAPIErrorMessage {
            get {
                return ResourceManager.GetString("NotSupportedAPIErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリンタ初期化エラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrinterErrorMessage {
            get {
                return ResourceManager.GetString("PrinterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷されませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrintErrorMessage {
            get {
                return ResourceManager.GetString("PrintErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プリンタの設定ファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrinterSettingErrorMessage {
            get {
                return ResourceManager.GetString("PrinterSettingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリーファイルが読み込まれていないのに実行しようとしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QueryExistsErrorMessage {
            get {
                return ResourceManager.GetString("QueryExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース結果列名と同じ印刷項目名が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QueryNotFieldErrorMessage {
            get {
                return ResourceManager.GetString("QueryNotFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース結果行が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QueryNotResultErrorMessage {
            get {
                return ResourceManager.GetString("QueryNotResultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のレコードが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecordErrorMessage {
            get {
                return ResourceManager.GetString("RecordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レコード名が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecordExistsErrorMessage {
            get {
                return ResourceManager.GetString("RecordExistsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定のレコードを出力すると現在のサブフォームを越してしまいます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecordPagingErrorMessage {
            get {
                return ResourceManager.GetString("RecordPagingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report Director Enterpriseサーバとの接続に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportDirectorConnectionErrorMessage {
            get {
                return ResourceManager.GetString("ReportDirectorConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report Director Enterpris e サーバでエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportDirectorServerErrorMessage {
            get {
                return ResourceManager.GetString("ReportDirectorServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report Director Enterprise にスプールする際､文書データの生成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportDirectorSpoolerErrorMessage {
            get {
                return ResourceManager.GetString("ReportDirectorSpoolerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイル読み込みエラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingErrorMessage {
            get {
                return ResourceManager.GetString("SettingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソートオブジェクトの作成エラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortErrorMessage {
            get {
                return ResourceManager.GetString("SortErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソートレコードの作成エラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortRecordErrorMessage {
            get {
                return ResourceManager.GetString("SortRecordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スプーラへの書き込みエラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpoolerErrorMessage {
            get {
                return ResourceManager.GetString("SpoolerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタックファイル作成エラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StackErrorMessage {
            get {
                return ResourceManager.GetString("StackErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サブフォームが無いにも関わらずレコードが指定されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubFormErrorMessage {
            get {
                return ResourceManager.GetString("SubFormErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SvfClient で致命的なAPIエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvfClientErrorMessage {
            get {
                return ResourceManager.GetString("SvfClientErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業用ファイルの作成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TemporaryErrorMessage {
            get {
                return ResourceManager.GetString("TemporaryErrorMessage", resourceCulture);
            }
        }
    }
}
