//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tos.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象データが存在しません。会社コード：{0}、{1}:{2}（AP0102）.
        /// </summary>
        internal static string AP0102 {
            get {
                return ResourceManager.GetString("AP0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適切なユーザーでログインしてください。.
        /// </summary>
        internal static string AuthenticationErrorMessage {
            get {
                return ResourceManager.GetString("AuthenticationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適切な権限のあるユーザーでログインしてください。.
        /// </summary>
        internal static string AuthorizedErrorMessage {
            get {
                return ResourceManager.GetString("AuthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページにアクセスする権限がありません。.
        /// </summary>
        internal static string AuthorizedErrorMessageTitle {
            get {
                return ResourceManager.GetString("AuthorizedErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製法文書_.
        /// </summary>
        internal static string BunshoExcelName {
            get {
                return ResourceManager.GetString("BunshoExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製法文書_製法番号_yyyyMMddhhmmss.
        /// </summary>
        internal static string BunshoTemplateExcelName {
            get {
                return ResourceManager.GetString("BunshoTemplateExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在しない部署コードが指定されています。.
        /// </summary>
        internal static string BushoNotfound {
            get {
                return ResourceManager.GetString("BushoNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string cd_category {
            get {
                return ResourceManager.GetString("cd_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string cd_category_25 {
            get {
                return ResourceManager.GetString("cd_category_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string cd_category_27 {
            get {
                return ResourceManager.GetString("cd_category_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string cd_jyotai_0 {
            get {
                return ResourceManager.GetString("cd_jyotai_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string cd_jyotai_1 {
            get {
                return ResourceManager.GetString("cd_jyotai_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string cd_jyotai_2 {
            get {
                return ResourceManager.GetString("cd_jyotai_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 調味料原価試算表.
        /// </summary>
        internal static string ChomiryoGenkaShisanHyoExcelName {
            get {
                return ResourceManager.GetString("ChomiryoGenkaShisanHyoExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【研＿調味料】原価試算フォーマット.
        /// </summary>
        internal static string ChomiryoGenkaShisanHyoTemplateExcelName {
            get {
                return ResourceManager.GetString("ChomiryoGenkaShisanHyoTemplateExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在しない{0}が指定されています。.
        /// </summary>
        internal static string CodeNotfound {
            get {
                return ResourceManager.GetString("CodeNotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 製法一覧.
        /// </summary>
        internal static string CSV200_Download {
            get {
                return ResourceManager.GetString("CSV200_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合明細.
        /// </summary>
        internal static string CSV203_DownloadDetail {
            get {
                return ResourceManager.GetString("CSV203_DownloadDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合製造ライン.
        /// </summary>
        internal static string CSV203_DownloadSeiho {
            get {
                return ResourceManager.GetString("CSV203_DownloadSeiho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合名マスタ.
        /// </summary>
        internal static string CSV208_Download {
            get {
                return ResourceManager.GetString("CSV208_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合製造ライン.
        /// </summary>
        internal static string CSV209_Download {
            get {
                return ResourceManager.GetString("CSV209_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合レシピ.
        /// </summary>
        internal static string CSV209_DownloadDetail {
            get {
                return ResourceManager.GetString("CSV209_DownloadDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原料一覧.
        /// </summary>
        internal static string CSV212_Download {
            get {
                return ResourceManager.GetString("CSV212_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv.
        /// </summary>
        internal static string CsvExtension {
            get {
                return ResourceManager.GetString("CsvExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロードでエラーが発生しています。
        ///アップロードしたファイルの下記のエラーを修正して再度アップロードしてください。.
        /// </summary>
        internal static string CSVUploadError {
            get {
                return ResourceManager.GetString("CSVUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データの保存に失敗しました。.
        /// </summary>
        internal static string DbSaveErrorMessage {
            get {
                return ResourceManager.GetString("DbSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すでに他のユーザーがこのデータを変更しています。最新のデータを取得してください。.
        /// </summary>
        internal static string DbUpdateConcurrencyError {
            get {
                return ResourceManager.GetString("DbUpdateConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string denso_zumi_status {
            get {
                return ResourceManager.GetString("denso_zumi_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部署内で品コードが重複しています。.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift-JIS.
        /// </summary>
        internal static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTF-8.
        /// </summary>
        internal static string EncodingUTF8 {
            get {
                return ResourceManager.GetString("EncodingUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーメッセージ.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーが発生しました。.
        /// </summary>
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー値.
        /// </summary>
        internal static string ErrorValue {
            get {
                return ResourceManager.GetString("ErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xlsx.
        /// </summary>
        internal static string ExcelExtension {
            get {
                return ResourceManager.GetString("ExcelExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xlsm.
        /// </summary>
        internal static string ExcelXlsmExtension {
            get {
                return ResourceManager.GetString("ExcelXlsmExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルダウンロードで出力する項目が選択されていません。.
        /// </summary>
        internal static string FileDownloadSelectErrorMessage {
            get {
                return ResourceManager.GetString("FileDownloadSelectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの保存に失敗しました。.
        /// </summary>
        internal static string FileSaveErrorMessage {
            get {
                return ResourceManager.GetString("FileSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを保存しました。.
        /// </summary>
        internal static string FileSaveSuccessMessage {
            get {
                return ResourceManager.GetString("FileSaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルサイズが{0}KB以上は保存できません。.
        /// </summary>
        internal static string FileSizeErrorMessage {
            get {
                return ResourceManager.GetString("FileSizeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string flag_eigyo {
            get {
                return ResourceManager.GetString("flag_eigyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string flag_honbu {
            get {
                return ResourceManager.GetString("flag_honbu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string flg_denso_taisho {
            get {
                return ResourceManager.GetString("flg_denso_taisho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string flg_mishiyo {
            get {
                return ResourceManager.GetString("flg_mishiyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グループコード.
        /// </summary>
        internal static string group_code {
            get {
                return ResourceManager.GetString("group_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合作成表_{0}_.
        /// </summary>
        internal static string HaigoSakuseiExcelName {
            get {
                return ResourceManager.GetString("HaigoSakuseiExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配合作成表_配合コード_yyyyMMddhhmmss.
        /// </summary>
        internal static string HaigoSakuseiTemplateExcelName {
            get {
                return ResourceManager.GetString("HaigoSakuseiTemplateExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string haishi {
            get {
                return ResourceManager.GetString("haishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string henshuchu_status {
            get {
                return ResourceManager.GetString("henshuchu_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string id_gamen_200 {
            get {
                return ResourceManager.GetString("id_gamen_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203.
        /// </summary>
        internal static string id_gamen_203 {
            get {
                return ResourceManager.GetString("id_gamen_203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string id_kino_100 {
            get {
                return ResourceManager.GetString("id_kino_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102.
        /// </summary>
        internal static string id_kino_102 {
            get {
                return ResourceManager.GetString("id_kino_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 103.
        /// </summary>
        internal static string id_kino_103 {
            get {
                return ResourceManager.GetString("id_kino_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string id_system_1 {
            get {
                return ResourceManager.GetString("id_system_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string id_system_2 {
            get {
                return ResourceManager.GetString("id_system_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string id_system_3 {
            get {
                return ResourceManager.GetString("id_system_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一括出力一覧.
        /// </summary>
        internal static string IkkatsuShutsuryokuIchiran {
            get {
                return ResourceManager.GetString("IkkatsuShutsuryokuIchiran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半角アルファベットのみで指定してください。.
        /// </summary>
        internal static string InvalidAlphabetError {
            get {
                return ResourceManager.GetString("InvalidAlphabetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半角アルファベット・数字のみで指定してください。.
        /// </summary>
        internal static string InvalidAlphabetNumberError {
            get {
                return ResourceManager.GetString("InvalidAlphabetNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ０/１もしくはTrue/Falseで指定してください。.
        /// </summary>
        internal static string InvalidBitFormatError {
            get {
                return ResourceManager.GetString("InvalidBitFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列数が不正です。.
        /// </summary>
        internal static string InvalidColumnSizeTextFieldFile {
            get {
                return ResourceManager.GetString("InvalidColumnSizeTextFieldFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日付フォーマットで指定してください。形式：{0}.
        /// </summary>
        internal static string InvalidDateFormatError {
            get {
                return ResourceManager.GetString("InvalidDateFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字で指定してください.
        /// </summary>
        internal static string InvalidDigitsFormatError {
            get {
                return ResourceManager.GetString("InvalidDigitsFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半角アルファベット・数字・記号のみで指定してください。.
        /// </summary>
        internal static string InvalidHankakuEiSuKigoError {
            get {
                return ResourceManager.GetString("InvalidHankakuEiSuKigoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半角のみで指定してください。.
        /// </summary>
        internal static string InvalidHankakuError {
            get {
                return ResourceManager.GetString("InvalidHankakuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半角カナのみで指定してください。.
        /// </summary>
        internal static string InvalidHankakuKanaError {
            get {
                return ResourceManager.GetString("InvalidHankakuKanaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整数値で指定してください.
        /// </summary>
        internal static string InvalidIntegerFormatError {
            get {
                return ResourceManager.GetString("InvalidIntegerFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数値で指定してください.
        /// </summary>
        internal static string InvalidNumberFormatError {
            get {
                return ResourceManager.GetString("InvalidNumberFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整数部{0}桁、小数点以下{1}桁までの数値を設定してください。.
        /// </summary>
        internal static string InvalidPointLengthFormatError {
            get {
                return ResourceManager.GetString("InvalidPointLengthFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーIDまたはパスワードが違います。.
        /// </summary>
        internal static string InvalidUserIdOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserIdOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーIDまたはパスワードが違います。もしくは有効期限が切れています。.
        /// </summary>
        internal static string InvalidUserIdOrPasswordOrExpire {
            get {
                return ResourceManager.GetString("InvalidUserIdOrPasswordOrExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全角のみで指定してください。.
        /// </summary>
        internal static string InvalidZenkakuError {
            get {
                return ResourceManager.GetString("InvalidZenkakuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自家原料.
        /// </summary>
        internal static string JikaGenyyo {
            get {
                return ResourceManager.GetString("JikaGenyyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string JushinchuStatus {
            get {
                return ResourceManager.GetString("JushinchuStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string KakuninStatus {
            get {
                return ResourceManager.GetString("KakuninStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _KategoriMaster_.
        /// </summary>
        internal static string KategoriMasterDownload {
            get {
                return ResourceManager.GetString("KategoriMasterDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string kbn_bumon_factory {
            get {
                return ResourceManager.GetString("kbn_bumon_factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string kbn_bumon_lab {
            get {
                return ResourceManager.GetString("kbn_bumon_lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string kbn_bunkatsu {
            get {
                return ResourceManager.GetString("kbn_bunkatsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string kbn_eigyo_1 {
            get {
                return ResourceManager.GetString("kbn_eigyo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string kbn_eigyo_2 {
            get {
                return ResourceManager.GetString("kbn_eigyo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string kbn_eigyo_3 {
            get {
                return ResourceManager.GetString("kbn_eigyo_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string kbn_haishi {
            get {
                return ResourceManager.GetString("kbn_haishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string kbn_hin {
            get {
                return ResourceManager.GetString("kbn_hin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string kbn_hin_haigo {
            get {
                return ResourceManager.GetString("kbn_hin_haigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string kbn_hin_shikakarihin {
            get {
                return ResourceManager.GetString("kbn_hin_shikakarihin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string kbn_kengen {
            get {
                return ResourceManager.GetString("kbn_kengen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 114.
        /// </summary>
        internal static string kengen_eigyo_114 {
            get {
                return ResourceManager.GetString("kengen_eigyo_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.
        /// </summary>
        internal static string kengen_eigyo_48 {
            get {
                return ResourceManager.GetString("kengen_eigyo_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string kengen_eigyo_50 {
            get {
                return ResourceManager.GetString("kengen_eigyo_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 権限コード.
        /// </summary>
        internal static string KengenCodeSaiban {
            get {
                return ResourceManager.GetString("KengenCodeSaiban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinLogin.aspx.
        /// </summary>
        internal static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGON_USER.
        /// </summary>
        internal static string LogonUser {
            get {
                return ResourceManager.GetString("LogonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string m_kirikae_foodprocs {
            get {
                return ResourceManager.GetString("m_kirikae_foodprocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string m_kirikae_hyoji {
            get {
                return ResourceManager.GetString("m_kirikae_hyoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}文字以内で入力してください。.
        /// </summary>
        internal static string Maxlenght {
            get {
                return ResourceManager.GetString("Maxlenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}文字以内で入力してください。.
        /// </summary>
        internal static string Maxmojisu {
            get {
                return ResourceManager.GetString("Maxmojisu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該当データが存在しません。.
        /// </summary>
        internal static string NoDataExsists {
            get {
                return ResourceManager.GetString("NoDataExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルが指定されていません。.
        /// </summary>
        internal static string NoFileAttachmentMessage {
            get {
                return ResourceManager.GetString("NoFileAttachmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルサイズが 0KB のためアップロードできません。.
        /// </summary>
        internal static string NoFileDataMessage {
            get {
                return ResourceManager.GetString("NoFileDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定されたファイルが存在しません。.
        /// </summary>
        internal static string NoFileExists {
            get {
                return ResourceManager.GetString("NoFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力されたコードがマスタに存在しません。.
        /// </summary>
        internal static string NoKeyDataExsists {
            get {
                return ResourceManager.GetString("NoKeyDataExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードの変更に失敗しました。.
        /// </summary>
        internal static string NotChangePassword {
            get {
                return ResourceManager.GetString("NotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL は許可されません。.
        /// </summary>
        internal static string NotNullAllow {
            get {
                return ResourceManager.GetString("NotNullAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップロードするデータが1件もありませんでした。.
        /// </summary>
        internal static string NoUploadDataError {
            get {
                return ResourceManager.GetString("NoUploadDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインしたユーザーの社員コードで社員マスタに情報が存在しませんでした。.
        /// </summary>
        internal static string NoUserExists {
            get {
                return ResourceManager.GetString("NoUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bit.
        /// </summary>
        internal static string NumberToBoolean {
            get {
                return ResourceManager.GetString("NumberToBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が指定桁数を超えています。半角{0}桁、全角{1}桁までで設定してください。.
        /// </summary>
        internal static string OutOfLengthTextField {
            get {
                return ResourceManager.GetString("OutOfLengthTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 値が範囲を超えています。{0} から {1} までの数値を設定してください。.
        /// </summary>
        internal static string OutOfRangeTextField {
            get {
                return ResourceManager.GetString("OutOfRangeTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プライマリキー制約違反です。.
        /// </summary>
        internal static string PrimaryKeyViolation {
            get {
                return ResourceManager.GetString("PrimaryKeyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルダウンロード処理中にサーバーで不明なエラーが発生しました。システム管理者に問い合わせしてください。.
        /// </summary>
        internal static string RaiseFileDownloadServerError {
            get {
                return ResourceManager.GetString("RaiseFileDownloadServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルアップロード処理中にサーバーで不明なエラーが発生しました。システム管理者に問い合わせしてください。.
        /// </summary>
        internal static string RaiseFileUploadServerError {
            get {
                return ResourceManager.GetString("RaiseFileUploadServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印刷処理中にサーバーで不明なエラーが発生しました。システム管理者に問い合わせしてください。.
        /// </summary>
        internal static string RaiseReportServerError {
            get {
                return ResourceManager.GetString("RaiseReportServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行.
        /// </summary>
        internal static string RecordNumber {
            get {
                return ResourceManager.GetString("RecordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __key.
        /// </summary>
        internal static string RequestClientKeyName {
            get {
                return ResourceManager.GetString("RequestClientKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必須の項目です。.
        /// </summary>
        internal static string RequiredTextField {
            get {
                return ResourceManager.GetString("RequiredTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&apos;content-type&apos; content=&apos;text/html; charset=UTF-8&apos; /&gt;
        ///        &lt;script type=&apos;text/javascript&apos;&gt;
        ///            if(window.parent &amp;&amp; window.parent.postMessage){{
        ///                    window.parent.postMessage(&apos;{0}&apos;,&apos;{1}&apos;);
        ///                }}
        ///        &lt;/script&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;div class=&apos;key&apos;&gt;{2}&lt;/div&gt; 
        ///        &lt;div class=&apos;result&apos;&gt;{3}&lt;/div&gt; 
        ///        &lt;div class=&apos;message&apos;&gt;{4}&lt;/div&gt; 
        ///        &lt;div class=&apos;data&apos;&gt;{5}&lt;/div&gt; 
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ResponseHtmlFormat {
            get {
                return ResourceManager.GetString("ResponseHtmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MixedSecurity.ReturnUrl.
        /// </summary>
        internal static string ReturnUrl {
            get {
                return ResourceManager.GetString("ReturnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゲート分類番号.
        /// </summary>
        internal static string saiban401Key1 {
            get {
                return ResourceManager.GetString("saiban401Key1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チェック番号.
        /// </summary>
        internal static string saiban402Key1 {
            get {
                return ResourceManager.GetString("saiban402Key1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示作成用フォーマット(調味料版).
        /// </summary>
        internal static string SakuseiFomattoExcel {
            get {
                return ResourceManager.GetString("SakuseiFomattoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サンプル説明書_合算.
        /// </summary>
        internal static string SakuseiFomattoExcelName {
            get {
                return ResourceManager.GetString("SakuseiFomattoExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サンプル説明書_アヲハタ（個別）.
        /// </summary>
        internal static string SanpuruSetsumeisho156Excel {
            get {
                return ResourceManager.GetString("SanpuruSetsumeisho156Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示作成用フォーマット(加食版).
        /// </summary>
        internal static string SanpuruSetsumeishoExcel {
            get {
                return ResourceManager.GetString("SanpuruSetsumeishoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サンプル説明書_個別.
        /// </summary>
        internal static string SanpuruSetsumeishoExcelName {
            get {
                return ResourceManager.GetString("SanpuruSetsumeishoExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設計品質ゲート_試作No_yyyyMMddhhmmss.
        /// </summary>
        internal static string SekkeiHinshutsuGetoExcelTemplate {
            get {
                return ResourceManager.GetString("SekkeiHinshutsuGetoExcelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設計品質ゲート_.
        /// </summary>
        internal static string SekkeiHinshutsuGetoExceName {
            get {
                return ResourceManager.GetString("SekkeiHinshutsuGetoExceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サービスでエラーが発生しました。.
        /// </summary>
        internal static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string shinsei_zumi_status {
            get {
                return ResourceManager.GetString("shinsei_zumi_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試作表(縦).
        /// </summary>
        internal static string ShisakuHaigoHyoOutputExcel {
            get {
                return ResourceManager.GetString("ShisakuHaigoHyoOutputExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試作表(縦バージョン).
        /// </summary>
        internal static string ShisakuHaigoHyoTemplateExcel {
            get {
                return ResourceManager.GetString("ShisakuHaigoHyoTemplateExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試作表_アヲハタ(横).
        /// </summary>
        internal static string ShisakuHyojiYoho153ExcelName {
            get {
                return ResourceManager.GetString("ShisakuHyojiYoho153ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試作表_アヲハタ(縦).
        /// </summary>
        internal static string ShisakuHyojiYoho154ExcelName {
            get {
                return ResourceManager.GetString("ShisakuHyojiYoho154ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試作表(横).
        /// </summary>
        internal static string ShisakuHyojiYohoExcelName {
            get {
                return ResourceManager.GetString("ShisakuHyojiYohoExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試作表(横バージョン).
        /// </summary>
        internal static string ShisakuHyojiYohoExcelTemplate {
            get {
                return ResourceManager.GetString("ShisakuHyojiYohoExcelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試算履歴順.
        /// </summary>
        internal static string shisanrirekijun {
            get {
                return ResourceManager.GetString("shisanrirekijun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Shonin2Status {
            get {
                return ResourceManager.GetString("Shonin2Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他原価試算表.
        /// </summary>
        internal static string SonotaGenkaShisanHyoExcelName {
            get {
                return ResourceManager.GetString("SonotaGenkaShisanHyoExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【研＿その他調味料以外】原価試算フォーマット.
        /// </summary>
        internal static string SonotaGenkaShisanHyoTemplateExcelName {
            get {
                return ResourceManager.GetString("SonotaGenkaShisanHyoTemplateExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 整数部8桁、小数部2桁以内で指定してください。.
        /// </summary>
        internal static string TankaMaxlenght {
            get {
                return ResourceManager.GetString("TankaMaxlenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 範囲内(0～99999999.99)で指定してください。.
        /// </summary>
        internal static string TankaOutOfRange {
            get {
                return ResourceManager.GetString("TankaOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チームコード.
        /// </summary>
        internal static string team_code {
            get {
                return ResourceManager.GetString("team_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明なエラーが発生しました。.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同一キーのデータが既に存在します。.
        /// </summary>
        internal static string ValidationKey {
            get {
                return ResourceManager.GetString("ValidationKey", resourceCulture);
            }
        }
    }
}
