/** 最終更新日 : 2018-02-28 **/
/**
 * グループオープン系システム共通基盤の Web アプリケーションで定義するメッセージです。
 */
(function () {

    App.define("App.messages.base", {
        required: "{name} field is required.  (BM0001)",
        digits: "please enter only numbers {name}.  (BM0002)",
        integer: "please enter only integer values ​​{name}.  (BM0003)",
        number: "please enter only numbers {name}.  (BM0004)",
        currency: "please input the amount of money {name}.  (BM0005)",
        min: "please input {param} more than {name}.  (BM0006)",
        max: "please input {param} following {name}.  (BM0007)",
        range: "please enter in the range {param [1]} of {param [0]} from the {name}.  (BM0008)",
        minlength: "please input {param} or more characters {name}.  (BM0009)",
        minbytelength: "please input {param} or more characters {name}.  (BM0010)",
        maxlength: "Please input {param} characters or less {name}.  (BM0011)",
        maxbytelength: "please input {param} characters or less {name}.  (BM0012)",
        rangelength: "please enter {param[1]} characters in {param[0]} or more characters {name}.  (BM0013)",
        rangebytelength: "please enter {param[1]} characters in {param[0]} or more characters {name}. (BM0013)",
        pointlength: "{param[0]} digits, please enter {param[1]} of digits after the decimal point is the decimal point {name}.  (BM0014)",
        date: "please enter a date in {name}.  (BM0015)",
        zenkaku: "please enter the full-width {name}.  (BM0016)",
        kana: "please enter double-byte Hiragana, Katakana {name}.  (BM0017)",
        hiragana: "please enter double-byte Hiragana {name}.  (BM0018)",
        katakana: "please enter the full-width katakana {name}.  (BM0019)",
        hankaku: "please enter the half-width {name}.  (BM0020)",
        haneisukigo: "please enter the alphanumeric symbols {name}.  (BM0021)",
        hankana: "please enter the half-width Katakana {name}.  (BM0022)",
        alphabet: "please enter the alphabetic characters is {name}.  (BM0023)",
        alphanum: "please enter alphanumeric characters is {name}.  (BM0024)",
        postnum: "the {name} Please enter a zip code (e.g.:123-4567).  (BM0025)",
        mobilenum: "the {name} please enter your mobile number (e.g.:010-2345-6789).  (BM0026)",
        telnum: "the {name} please enter your phone number (e.g.:012-345-6789).  (BM0027)",
        illegalchara: "the {name} not allowed input character has been input (e.g.:'{).  (BM0028)",
        datestring: "please enter in yyyy/mm/dd format is {name}.  (BM0029)",
        lessdate: "please enter the date of {lessdate} after {name}.  (BM0030)",
        greaterdate: "please enter the date of {greaterdate} previous {name}.  (BM0031)",
        equallength: "please input {param} digits {name}.  (BM0032)",
        exit: "content has changed, Are you sure you want to quit?  (BM0033)",
        selectfile: "select a file.  (BM0034)",
        uploadsuccess: "file upload was successful.  (BM0035)",
        fileexist: "file with the same name exists.  (BM0036)",
        uploaderror: "file upload was error. please check an error CSV file.  (BM0037)",
        csvonly: "upload file extension is csv only.  (BM0038)",
        currencyjpmax: "please input {param} following {name}.  (BM0039)",
        datestringYM: "please enter in yyyy/mm format is {name}.  (BM0040)",
        uploadServerError: "an unknown error occurred during the upload process. please contact the support center.(BM0041)",
        MS0001: "the current password and the new password is not possible to specify the same thing.  (MS0001）",
        MS0002: "storage process is complete.  (MS0002)",
        MS0003: "it will delete this data. is it OK? (MS0003)",
        MS0004: "it will delete the selected row. is it OK? (MS0004)", 
        MS0005: "failed in CSV File output.(MS0005)",
        MS0006: "failed to save processing. please contact the support center.  (MS0006)",
        MS0007: "new password and confirmation password do not match. (MS0007)",
        MS0008: "removal process is complete.  (MS0008)",
        MS0009: "for if you did not change the data I've already re-obtain the latest data.  (MS0009)",
        MS0010: "search condition has been changed. Please search again.  (MS0010)",
        MS0011: "exceeded the maximum number can be displayed. Please search again and squeeze the search criteria.  (MS0011)",
        MS0012: "data to be printed is not selected.  (MS0012)",
        MS0013: "data already exists.  (MS0013)",
        MS0014: "please specify a past date than the end date is the start date.  (MS0014)",
        MS0015: "data corresponding to the code does not exist.  (MS0015)",
        MS0016: "failed in Excel output.  (MS0016)",
        MS0017: "another user has changed the data already. Please to get the most up-to-date data.  (MS0017)",
        MS0018: "please put the upload file name {param} characters or less. (MS0018)",
        MS0019: "failed to upload file [{nm_file}] : {nm_message}  (MS0019)",
        MS0020: "please select a choice of one or more. (MS0020)",
        MS0021: "please include in your password three or more kinds among the uppercase, lowercase letters, numbers and symbols.  (MS0021)",
        MS0022: "it can not be uploaded because the file size is 0KB. : {nm_file} (MS0022)",
        MS0023: "it can not save because the file size is over {size}KB. : {nm_file} (MS0023)"
    });

})();
