//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FOODPROCSEntities : DbContext
    {
        public FOODPROCSEntities()
            : base("name=FOODPROCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ma_bunrui> ma_bunrui { get; set; }
        public DbSet<ma_genshizai> ma_genshizai { get; set; }
        public DbSet<ma_haigo_mei> ma_haigo_mei { get; set; }
        public DbSet<ma_haigo_mei_hyoji> ma_haigo_mei_hyoji { get; set; }
        public DbSet<ma_haigo_recipe> ma_haigo_recipe { get; set; }
        public DbSet<ma_haigo_recipe_hyoji> ma_haigo_recipe_hyoji { get; set; }
        public DbSet<ma_kojyo> ma_kojyo { get; set; }
        public DbSet<ma_konpo> ma_konpo { get; set; }
        public DbSet<ma_line> ma_line { get; set; }
        public DbSet<ma_maeshori> ma_maeshori { get; set; }
        public DbSet<ma_mark> ma_mark { get; set; }
        public DbSet<ma_sagyo> ma_sagyo { get; set; }
        public DbSet<ma_seihin> ma_seihin { get; set; }
        public DbSet<ma_seizo_line> ma_seizo_line { get; set; }
        public DbSet<ma_seizo_line_hyoji> ma_seizo_line_hyoji { get; set; }
        public DbSet<ma_setsubi> ma_setsubi { get; set; }
        public DbSet<ma_tani> ma_tani { get; set; }
        public DbSet<ma_tanto> ma_tanto { get; set; }
        public DbSet<SS_vw_hin> SS_vw_hin { get; set; }
        public DbSet<SS_vw_hin_hyoji> SS_vw_hin_hyoji { get; set; }
        public DbSet<SS_vw_hin_varchar> SS_vw_hin_varchar { get; set; }
        public DbSet<SS_vw_hin_varchar_hyoji> SS_vw_hin_varchar_hyoji { get; set; }
        public DbSet<vw_ma_haigo_mei_hyoji> vw_ma_haigo_mei_hyoji { get; set; }
        public DbSet<vw_ma_haigo_recipe_hyoji> vw_ma_haigo_recipe_hyoji { get; set; }
        public DbSet<vw_ma_haigo_mei> vw_ma_haigo_mei { get; set; }
        public DbSet<vw_ma_haigo_recipe> vw_ma_haigo_recipe { get; set; }
        public DbSet<vw_ma_mark> vw_ma_mark { get; set; }
    
        public virtual ObjectResult<SS_Hin_Check_sp_Result> SS_Hin_Check_sp(string cd_hin, Nullable<int> su_hinCD)
        {
            var cd_hinParameter = cd_hin != null ?
                new ObjectParameter("cd_hin", cd_hin) :
                new ObjectParameter("cd_hin", typeof(string));
    
            var su_hinCDParameter = su_hinCD.HasValue ?
                new ObjectParameter("su_hinCD", su_hinCD) :
                new ObjectParameter("su_hinCD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_Hin_Check_sp_Result>("SS_Hin_Check_sp", cd_hinParameter, su_hinCDParameter);
        }
    
        public virtual ObjectResult<SS_Hin_Check_sp_hyoji_Result> SS_Hin_Check_sp_hyoji(string cd_hin, Nullable<int> su_hinCD)
        {
            var cd_hinParameter = cd_hin != null ?
                new ObjectParameter("cd_hin", cd_hin) :
                new ObjectParameter("cd_hin", typeof(string));
    
            var su_hinCDParameter = su_hinCD.HasValue ?
                new ObjectParameter("su_hinCD", su_hinCD) :
                new ObjectParameter("su_hinCD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_Hin_Check_sp_hyoji_Result>("SS_Hin_Check_sp_hyoji", cd_hinParameter, su_hinCDParameter);
        }
    
        public virtual ObjectResult<SS_Hin_Check_sp_hyoji_qpnmacs_Result> SS_Hin_Check_sp_hyoji_qpnmacs(string cd_hin, Nullable<int> su_hinCD)
        {
            var cd_hinParameter = cd_hin != null ?
                new ObjectParameter("cd_hin", cd_hin) :
                new ObjectParameter("cd_hin", typeof(string));
    
            var su_hinCDParameter = su_hinCD.HasValue ?
                new ObjectParameter("su_hinCD", su_hinCD) :
                new ObjectParameter("su_hinCD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_Hin_Check_sp_hyoji_qpnmacs_Result>("SS_Hin_Check_sp_hyoji_qpnmacs", cd_hinParameter, su_hinCDParameter);
        }
    
        public virtual ObjectResult<SS_Hin_Check_sp_qpnmacs_Result> SS_Hin_Check_sp_qpnmacs(string cd_hin, Nullable<int> su_hinCD)
        {
            var cd_hinParameter = cd_hin != null ?
                new ObjectParameter("cd_hin", cd_hin) :
                new ObjectParameter("cd_hin", typeof(string));
    
            var su_hinCDParameter = su_hinCD.HasValue ?
                new ObjectParameter("su_hinCD", su_hinCD) :
                new ObjectParameter("su_hinCD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SS_Hin_Check_sp_qpnmacs_Result>("SS_Hin_Check_sp_qpnmacs", cd_hinParameter, su_hinCDParameter);
        }
    }
}
