//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_haigo_mei
    {
        public int no_seq { get; set; }
        public string cd_haigo { get; set; }
        public string nm_haigo { get; set; }
        public string nm_haigo_r { get; set; }
        public string kbn_hin { get; set; }
        public string cd_bunrui { get; set; }
        public double budomari { get; set; }
        public int qty_kihon { get; set; }
        public Nullable<double> ritsu_kihon { get; set; }
        public string cd_setsubi { get; set; }
        public bool flg_gasan { get; set; }
        public Nullable<double> qty_max { get; set; }
        public int no_han { get; set; }
        public int qty_haigo_h { get; set; }
        public Nullable<double> qty_haigo_kei { get; set; }
        public string biko { get; set; }
        public string no_seiho { get; set; }
        public string cd_tanto_seizo { get; set; }
        public Nullable<System.DateTime> dt_seizo { get; set; }
        public string cd_tanto_hinkan { get; set; }
        public Nullable<System.DateTime> dt_hinkan { get; set; }
        public System.DateTime dt_from { get; set; }
        public System.DateTime dt_to { get; set; }
        public string kbn_vw { get; set; }
        public Nullable<double> hijyu { get; set; }
        public bool flg_shorihin { get; set; }
        public bool flg_hinkan { get; set; }
        public bool flg_seizo { get; set; }
        public bool flg_sakujyo { get; set; }
        public bool flg_mishiyo { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public System.DateTime dt_henko { get; set; }
        public string cd_koshin { get; set; }
        public Nullable<bool> kbn_shiagari { get; set; }
        public string nm_haigo_rm { get; set; }
        public string cd_haigo_seiho { get; set; }
        public Nullable<bool> flg_seiho_base { get; set; }
        public string nm_seiho { get; set; }
        public Nullable<byte> kbn_koshin { get; set; }
        public Nullable<double> kin_keihi { get; set; }
        public Nullable<bool> flg_tenkai { get; set; }
        public Nullable<double> qty_haigo_auto { get; set; }
        public Nullable<int> su_kigen_min { get; set; }
        public Nullable<int> su_kigen_max { get; set; }
        public Nullable<bool> flg_mishiyo_seizo { get; set; }
        public Nullable<double> qty_kowake { get; set; }
        public Nullable<int> su_kowake { get; set; }
        public Nullable<int> kikan_shomi { get; set; }
        public Nullable<int> qty_haigo_genka { get; set; }
        public Nullable<int> no_han_genka { get; set; }
        public Nullable<bool> flg_unten { get; set; }
        public string cd_tanto_unten { get; set; }
        public Nullable<System.DateTime> dt_unten { get; set; }
    }
}
