//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_kojyo
    {
        public string cd_kojyo { get; set; }
        public string cd_kaisha { get; set; }
        public string nm_kojyo { get; set; }
        public string no_yubin { get; set; }
        public string jyusho_1 { get; set; }
        public string jyusho_2 { get; set; }
        public string jyusho_3 { get; set; }
        public string tel_1 { get; set; }
        public string tel_2 { get; set; }
        public string fax_1 { get; set; }
        public string fax_2 { get; set; }
        public Nullable<bool> flg_sakujyo { get; set; }
        public System.DateTime dt_kakutei { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public Nullable<System.DateTime> dt_henko { get; set; }
        public string cd_koshin { get; set; }
        public System.Guid rowguid { get; set; }
        public string flg_ean { get; set; }
        public int param_edi_densokaishi { get; set; }
        public int param_edi_saishodenso { get; set; }
        public string cd_jigyobu_default { get; set; }
        public string cd_depo_default { get; set; }
        public string cd_jigyosho_default { get; set; }
        public string literal_iraisho { get; set; }
        public string literal_iraisho_shokuyu { get; set; }
        public Nullable<System.DateTime> dt_joken_shiharai { get; set; }
        public string tekiyo { get; set; }
        public Nullable<System.DateTime> dt_data_kakutei { get; set; }
    }
}
