//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_konpo
    {
        public int no_seq { get; set; }
        public string cd_hin { get; set; }
        public Nullable<double> nisugata_qty { get; set; }
        public string nisugata_hyoji { get; set; }
        public int su_iri { get; set; }
        public double qty { get; set; }
        public Nullable<int> su_iri_banju { get; set; }
        public string kbn_hako { get; set; }
        public string cd_jan { get; set; }
        public Nullable<int> su_uchibako { get; set; }
        public Nullable<int> su_sotobako { get; set; }
        public Nullable<int> su_palette { get; set; }
        public Nullable<bool> kbn_data_convert { get; set; }
        public string cd_hanbai_1 { get; set; }
        public string cd_hanbai_2 { get; set; }
        public Nullable<double> kin_keihi { get; set; }
        public Nullable<int> su_noritsu { get; set; }
        public string cd_shukei { get; set; }
        public string kbn_ksys_denso { get; set; }
        public string kbn_ksys_dekidaka { get; set; }
        public string cd_bunrui { get; set; }
        public Nullable<bool> kbn_tenkai { get; set; }
        public string nm_hin_tag { get; set; }
        public string kbn_itaku { get; set; }
        public Nullable<int> su_batch_dekidaka { get; set; }
        public bool flg_sakujyo { get; set; }
        public bool flg_mishiyo { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public System.DateTime dt_henko { get; set; }
        public string cd_koshin { get; set; }
        public System.Guid rowguid { get; set; }
        public string cd_tani_keiri { get; set; }
    }
}
