//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_line
    {
        public int no_seq { get; set; }
        public string cd_line { get; set; }
        public string nm_line { get; set; }
        public string cd_shokuba { get; set; }
        public string cd_team { get; set; }
        public bool flg_shuka_2 { get; set; }
        public bool flg_sakujyo { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public System.DateTime dt_henko { get; set; }
        public string cd_koshin { get; set; }
        public System.Guid rowguid { get; set; }
        public string cd_line_2 { get; set; }
        public Nullable<int> time_hayade_seizo_minute { get; set; }
        public Nullable<bool> flg_egg { get; set; }
        public Nullable<int> no_hyoji { get; set; }
        public string cd_pallet_line { get; set; }
        public Nullable<bool> flg_autorack_denso { get; set; }
    }
}
