//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_maeshori
    {
        public int no_seq { get; set; }
        public string cd_maeshori { get; set; }
        public string nm_maeshori { get; set; }
        public string nm_maeshori_r { get; set; }
        public string nm_maeshori_rm { get; set; }
        public string cd_hin { get; set; }
        public string shiji_sagyo { get; set; }
        public string cd_setsubi { get; set; }
        public Nullable<int> su_jyunbi { get; set; }
        public string cd_hini { get; set; }
        public double budomari { get; set; }
        public string biko { get; set; }
        public string cd_shukei { get; set; }
        public string jikan_hinon { get; set; }
        public Nullable<double> percent_shio { get; set; }
        public string nm_tenkabutsu { get; set; }
        public Nullable<double> percent_tenkabutsu { get; set; }
        public string hoho_reikyaku { get; set; }
        public bool flg_sakujyo { get; set; }
        public bool flg_mishiyo { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public System.DateTime dt_henko { get; set; }
        public string cd_koshin { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<double> budomari_second { get; set; }
    }
}
