//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_setsubi
    {
        public int no_seq { get; set; }
        public string cd_shokuba { get; set; }
        public string cd_setsubi { get; set; }
        public string nm_setsubi { get; set; }
        public bool flg_sakujyo { get; set; }
        public bool flg_mishiyo { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public System.DateTime dt_henko { get; set; }
        public string cd_koshin { get; set; }
        public Nullable<int> no_node { get; set; }
        public Nullable<int> no_kotei { get; set; }
        public Nullable<bool> kbn_jyushin { get; set; }
        public string flg_line { get; set; }
    }
}
