//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seihin
    {
        public int no_seq { get; set; }
        public string cd_hin { get; set; }
        public string nm_hin { get; set; }
        public string nm_hin_r { get; set; }
        public string nm_hin_rm { get; set; }
        public string cd_tani_jyuchu { get; set; }
        public string cd_tani_shiyo { get; set; }
        public string cd_niuke { get; set; }
        public Nullable<double> budomari { get; set; }
        public Nullable<double> hijyu { get; set; }
        public string kbn_jyotai { get; set; }
        public Nullable<double> su_saitei { get; set; }
        public Nullable<int> kikan_shomi { get; set; }
        public string tani_shomi { get; set; }
        public Nullable<int> kikan_shomi_kaifu { get; set; }
        public string tani_shomi_kaifu { get; set; }
        public string cd_hini { get; set; }
        public Nullable<double> kin_romu { get; set; }
        public string cd_haigo { get; set; }
        public Nullable<int> no_yusen { get; set; }
        public string cd_haigo_hyoji { get; set; }
        public Nullable<int> no_yusen_hyoji { get; set; }
        public Nullable<double> kin_tanka { get; set; }
        public string kbn_seisan { get; set; }
        public string biko { get; set; }
        public string kbn_seihin { get; set; }
        public string kbn_kuraire { get; set; }
        public string kbn_vw { get; set; }
        public Nullable<int> su_leadtime { get; set; }
        public string cd_tani_nonyu { get; set; }
        public string kbn_zei { get; set; }
        public Nullable<double> kin_tanka_nonyu { get; set; }
        public bool flg_sakujyo { get; set; }
        public bool flg_mishiyo { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public System.DateTime dt_henko { get; set; }
        public string cd_koshin { get; set; }
        public Nullable<int> cd_spu { get; set; }
        public Nullable<int> kbn_genryohin { get; set; }
        public Nullable<double> kin_genka { get; set; }
        public string no_kikaku { get; set; }
        public string nm_kikaku { get; set; }
        public string cd_hini_gmat { get; set; }
        public string nm_seizo { get; set; }
        public string nm_hanbai { get; set; }
        public Nullable<System.DateTime> dt_toroku_kikaku { get; set; }
        public string nm_bussitsu { get; set; }
        public string cd_doto_hin { get; set; }
        public Nullable<System.DateTime> dt_doto_SET_DATE { get; set; }
        public string cd_doto_kaisha { get; set; }
        public string cd_itf { get; set; }
        public string kbn_kisan_shomi { get; set; }
        public Nullable<int> kikan_shomi_kaifu2 { get; set; }
        public string tani_shomi_kaifu2 { get; set; }
        public string kbn_hokan_kaifu1 { get; set; }
        public string kbn_hokan_kaifu2 { get; set; }
        public Nullable<double> su_saidai { get; set; }
        public Nullable<double> kin_tanka_shiire { get; set; }
        public string cd_kura { get; set; }
        public string cd_shokuba_hachu { get; set; }
        public Nullable<double> kin_tanka_zaiko { get; set; }
        public string kbn_shiyo_tanka { get; set; }
        public string kbn_uri { get; set; }
        public string cd_route_uriage { get; set; }
        public bool kbn_deki { get; set; }
        public bool kbn_kura { get; set; }
        public bool kbn_auto_kura { get; set; }
        public bool kbn_azuke_kura { get; set; }
        public bool kbn_alarm_zaiko { get; set; }
        public bool kbn_jit { get; set; }
        public Nullable<double> kbn_rat_shomi { get; set; }
        public string cd_route { get; set; }
        public string cd_tani_a { get; set; }
        public string cd_tani_b { get; set; }
        public string cd_kamoku_b { get; set; }
        public string kbn_genryo_shiyo { get; set; }
        public string cd_basho_kowake { get; set; }
        public Nullable<double> kin_tanka_nisugata { get; set; }
        public string kbn_conv_1 { get; set; }
        public string kbn_conv_2 { get; set; }
        public string kbn_conv_3 { get; set; }
        public string kbn_shokuba { get; set; }
        public Nullable<double> su_kanzan_kama { get; set; }
        public Nullable<byte> kbn_sakusei { get; set; }
        public string cd_depo { get; set; }
        public Nullable<double> su_jinin { get; set; }
        public string cd_haigo2 { get; set; }
        public string kbn_check { get; set; }
        public string kbn_check_date { get; set; }
        public string kbn_sanshutsu { get; set; }
        public Nullable<int> kikan_shomi_refreeze { get; set; }
        public Nullable<int> kikan_shomi_rethawing { get; set; }
        public Nullable<bool> kbn_hakodume { get; set; }
        public string no_location { get; set; }
        public string kbn_labelnyukohyo { get; set; }
        public Nullable<double> kin_tanka_shiire_new { get; set; }
        public Nullable<System.DateTime> dt_tanka_shiire_new { get; set; }
        public Nullable<double> kin_tanka_nisugata_new { get; set; }
        public Nullable<System.DateTime> dt_tanka_nisugata_new { get; set; }
        public Nullable<int> su_leadtime_hachu { get; set; }
        public Nullable<int> su_leadtime_irai_from { get; set; }
        public Nullable<int> su_leadtime_irai_to { get; set; }
        public Nullable<bool> kbn_unmatch { get; set; }
        public Nullable<bool> kbn_shiyo { get; set; }
        public Nullable<decimal> zan_futai { get; set; }
        public Nullable<double> su_hiritsu { get; set; }
        public Nullable<double> su_hiritsu2 { get; set; }
        public Nullable<bool> flg_kanri_jika { get; set; }
        public Nullable<int> su_ageing { get; set; }
        public Nullable<bool> flg_mishiyo_seizo { get; set; }
    }
}
