//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_tanto
    {
        public int no_seq { get; set; }
        public string cd_tanto { get; set; }
        public string nm_tanto { get; set; }
        public string cd_password { get; set; }
        public string nm_shozoku { get; set; }
        public string renraku { get; set; }
        public string e_mail { get; set; }
        public Nullable<bool> flg_kengen_1 { get; set; }
        public Nullable<bool> flg_kengen_2 { get; set; }
        public Nullable<bool> flg_kengen_3 { get; set; }
        public Nullable<bool> flg_kengen_4 { get; set; }
        public Nullable<bool> flg_kengen_5 { get; set; }
        public Nullable<bool> flg_kengen_6 { get; set; }
        public Nullable<bool> flg_kengen_7 { get; set; }
        public Nullable<bool> flg_kengen_8 { get; set; }
        public Nullable<bool> flg_kengen_9 { get; set; }
        public Nullable<bool> flg_kengen_10 { get; set; }
        public Nullable<bool> flg_kengen_11 { get; set; }
        public Nullable<bool> flg_kengen_12 { get; set; }
        public Nullable<bool> flg_kengen_13 { get; set; }
        public string flg_login { get; set; }
        public Nullable<bool> flg_mrp { get; set; }
        public Nullable<bool> flg_sakujyo { get; set; }
        public Nullable<bool> flg_mishiyo { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<System.DateTime> dt_henko { get; set; }
        public string cd_koshin { get; set; }
        public string cd_ope { get; set; }
        public string cd_shokuba { get; set; }
        public Nullable<bool> flg_hakari { get; set; }
        public Nullable<bool> flg_jitsusakujyo { get; set; }
        public Nullable<bool> flg_shikakari { get; set; }
        public Nullable<bool> flg_saikin { get; set; }
        public Nullable<bool> flg_harikae { get; set; }
        public Nullable<System.DateTime> dt_henko_password { get; set; }
        public Nullable<System.DateTime> dt_login { get; set; }
        public Nullable<bool> flg_shokuyu_haigo_hiritsu { get; set; }
        public Nullable<bool> flg_genshizai_chotatsu_bu { get; set; }
        public Nullable<bool> flg_bun_master { get; set; }
        public Nullable<bool> flg_bun_shiyaku { get; set; }
        public Nullable<bool> flg_bun_tanto { get; set; }
    }
}
