//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_vw_hin_varchar
    {
        public string cd_hin { get; set; }
        public string nm_hin { get; set; }
        public Nullable<double> hijyu { get; set; }
        public Nullable<double> budomari { get; set; }
        public string no_kikaku { get; set; }
        public int kbn_hin { get; set; }
        public int kbn_hin_toroku { get; set; }
        public string cd_tani_hin { get; set; }
        public Nullable<double> nisugata_gty { get; set; }
        public Nullable<int> kbn_jyotai { get; set; }
    }
}
