//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.DataFP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ma_haigo_recipe_hyoji
    {
        public int no_seq { get; set; }
        public string cd_haigo { get; set; }
        public int no_han { get; set; }
        public int qty_haigo_h { get; set; }
        public int no_kotei { get; set; }
        public int no_tonyu { get; set; }
        public string cd_hin { get; set; }
        public string kbn_hin { get; set; }
        public string nm_hin { get; set; }
        public string cd_mark { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> qty_haigo { get; set; }
        public Nullable<double> qty_nisugata { get; set; }
        public Nullable<int> su_nisugata { get; set; }
        public Nullable<double> qty_kowake { get; set; }
        public Nullable<int> su_kowake { get; set; }
        public string cd_futai { get; set; }
        public Nullable<double> qty_futai { get; set; }
        public Nullable<double> hijyu { get; set; }
        public Nullable<double> budomari { get; set; }
        public bool flg_sakujyo { get; set; }
        public bool flg_mishiyo { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public System.DateTime dt_henko { get; set; }
        public string cd_koshin { get; set; }
        public string kbn_jyotai { get; set; }
        public string kbn_shitei { get; set; }
        public byte kbn_bunkatsu { get; set; }
    }
}
