//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QPDATA2Entities : DbContext
    {
        public QPDATA2Entities()
            : base("name=QPDATA2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int sp_shohinkaihatsu_g3_save_202(string id_user, Nullable<int> cd_hin, Nullable<decimal> no_han, string kbn_meisho, string nm_meisho_hinmei, string kbn_shomikikan, string kbn_shomikikan_seizo_fukumu, Nullable<int> su_shomikikan_free_input, string kbn_shomikikan_tani, string su_naiyoryo, Nullable<int> cd_naiyoryo_tani, Nullable<int> nm_toriatsukai_ondo, string nm_seihintokusechi_kenshisakuhin, string no_seiho, string cd_kaisha, ObjectParameter g3_kekka)
        {
            var id_userParameter = id_user != null ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(string));
    
            var cd_hinParameter = cd_hin.HasValue ?
                new ObjectParameter("cd_hin", cd_hin) :
                new ObjectParameter("cd_hin", typeof(int));
    
            var no_hanParameter = no_han.HasValue ?
                new ObjectParameter("no_han", no_han) :
                new ObjectParameter("no_han", typeof(decimal));
    
            var kbn_meishoParameter = kbn_meisho != null ?
                new ObjectParameter("kbn_meisho", kbn_meisho) :
                new ObjectParameter("kbn_meisho", typeof(string));
    
            var nm_meisho_hinmeiParameter = nm_meisho_hinmei != null ?
                new ObjectParameter("nm_meisho_hinmei", nm_meisho_hinmei) :
                new ObjectParameter("nm_meisho_hinmei", typeof(string));
    
            var kbn_shomikikanParameter = kbn_shomikikan != null ?
                new ObjectParameter("kbn_shomikikan", kbn_shomikikan) :
                new ObjectParameter("kbn_shomikikan", typeof(string));
    
            var kbn_shomikikan_seizo_fukumuParameter = kbn_shomikikan_seizo_fukumu != null ?
                new ObjectParameter("kbn_shomikikan_seizo_fukumu", kbn_shomikikan_seizo_fukumu) :
                new ObjectParameter("kbn_shomikikan_seizo_fukumu", typeof(string));
    
            var su_shomikikan_free_inputParameter = su_shomikikan_free_input.HasValue ?
                new ObjectParameter("su_shomikikan_free_input", su_shomikikan_free_input) :
                new ObjectParameter("su_shomikikan_free_input", typeof(int));
    
            var kbn_shomikikan_taniParameter = kbn_shomikikan_tani != null ?
                new ObjectParameter("kbn_shomikikan_tani", kbn_shomikikan_tani) :
                new ObjectParameter("kbn_shomikikan_tani", typeof(string));
    
            var su_naiyoryoParameter = su_naiyoryo != null ?
                new ObjectParameter("su_naiyoryo", su_naiyoryo) :
                new ObjectParameter("su_naiyoryo", typeof(string));
    
            var cd_naiyoryo_taniParameter = cd_naiyoryo_tani.HasValue ?
                new ObjectParameter("cd_naiyoryo_tani", cd_naiyoryo_tani) :
                new ObjectParameter("cd_naiyoryo_tani", typeof(int));
    
            var nm_toriatsukai_ondoParameter = nm_toriatsukai_ondo.HasValue ?
                new ObjectParameter("nm_toriatsukai_ondo", nm_toriatsukai_ondo) :
                new ObjectParameter("nm_toriatsukai_ondo", typeof(int));
    
            var nm_seihintokusechi_kenshisakuhinParameter = nm_seihintokusechi_kenshisakuhin != null ?
                new ObjectParameter("nm_seihintokusechi_kenshisakuhin", nm_seihintokusechi_kenshisakuhin) :
                new ObjectParameter("nm_seihintokusechi_kenshisakuhin", typeof(string));
    
            var no_seihoParameter = no_seiho != null ?
                new ObjectParameter("no_seiho", no_seiho) :
                new ObjectParameter("no_seiho", typeof(string));
    
            var cd_kaishaParameter = cd_kaisha != null ?
                new ObjectParameter("cd_kaisha", cd_kaisha) :
                new ObjectParameter("cd_kaisha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_shohinkaihatsu_g3_save_202", id_userParameter, cd_hinParameter, no_hanParameter, kbn_meishoParameter, nm_meisho_hinmeiParameter, kbn_shomikikanParameter, kbn_shomikikan_seizo_fukumuParameter, su_shomikikan_free_inputParameter, kbn_shomikikan_taniParameter, su_naiyoryoParameter, cd_naiyoryo_taniParameter, nm_toriatsukai_ondoParameter, nm_seihintokusechi_kenshisakuhinParameter, no_seihoParameter, cd_kaishaParameter, g3_kekka);
        }
    }
}
