//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_busho
    {
        public int cd_kaisha { get; set; }
        public int cd_busho { get; set; }
        public string nm_kaisha { get; set; }
        public string nm_busho { get; set; }
        public short keta_genryo { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<short> fg_hyoji { get; set; }
        public Nullable<short> flg_kenkyu { get; set; }
        public Nullable<short> flg_seisan { get; set; }
        public Nullable<short> flg_genshizai { get; set; }
        public Nullable<short> flg_kojo { get; set; }
        public Nullable<short> flg_eigyo { get; set; }
        public Nullable<short> flg_honbu { get; set; }
    }
}
