//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_genryo
    {
        public int cd_kaisha { get; set; }
        public string cd_genryo { get; set; }
        public Nullable<decimal> ritu_sakusan { get; set; }
        public Nullable<decimal> ritu_shokuen { get; set; }
        public Nullable<decimal> ritu_sousan { get; set; }
        public Nullable<decimal> ritu_abura { get; set; }
        public string hyojian { get; set; }
        public string tenkabutu { get; set; }
        public string memo { get; set; }
        public string no_eiyo1 { get; set; }
        public string no_eiyo2 { get; set; }
        public string no_eiyo3 { get; set; }
        public string no_eiyo4 { get; set; }
        public string no_eiyo5 { get; set; }
        public string wariai1 { get; set; }
        public string wariai2 { get; set; }
        public string wariai3 { get; set; }
        public string wariai4 { get; set; }
        public string wariai5 { get; set; }
        public short kbn_haishi { get; set; }
        public string cd_kakutei { get; set; }
        public Nullable<decimal> id_kakunin { get; set; }
        public Nullable<System.DateTime> dt_kakunin { get; set; }
        public decimal id_toroku { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public decimal id_koshin { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public Nullable<decimal> ritu_msg { get; set; }
        public string nisugata_hyoji { get; set; }
        public string rank_ibutsu { get; set; }
        public string shiyokahi_genryo { get; set; }
        public string shiyokahi_riyu { get; set; }
        public string shiyokahi_cd_genryo_daitai { get; set; }
        public string shiyokahi_nm_genryo_daitai { get; set; }
        public string trouble_joho { get; set; }
        public string trouble_gaiyo { get; set; }
        public string trouble_naiyo_shosai { get; set; }
        public string sakkin_chomieki_yohi { get; set; }
        public string sakkin_chomieki_joken { get; set; }
        public string NB_genteigenryo { get; set; }
        public string NB_joken { get; set; }
        public string NB_riyu { get; set; }
        public string kasseikoso { get; set; }
        public string gosei_tenkabutu { get; set; }
        public string biko { get; set; }
        public byte[] ts { get; set; }
        public Nullable<decimal> id_koshin_shisaquicklab { get; set; }
        public Nullable<System.DateTime> dt_koshin_shisaquicklab { get; set; }
        public Nullable<short> flg_gensanchi { get; set; }
        public Nullable<System.DateTime> dt_gensanchi { get; set; }
    }
}
