//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_genryo_bf
    {
        public int cd_kaisha { get; set; }
        public string cd_genryo { get; set; }
        public Nullable<decimal> wt_kaniku { get; set; }
        public Nullable<decimal> wt_sato { get; set; }
        public Nullable<decimal> wt_kanmido { get; set; }
        public Nullable<decimal> wt_hiju { get; set; }
        public Nullable<decimal> wt_ireme { get; set; }
        public Nullable<decimal> wt_1_kan { get; set; }
        public Nullable<short> kbn_sato { get; set; }
        public Nullable<short> kbn_gum { get; set; }
        public Nullable<byte> cd_tani_master { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public byte[] ts { get; set; }
        public string memo { get; set; }
    }
}
