//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_genryokojo
    {
        public int cd_kaisha { get; set; }
        public string cd_genryo { get; set; }
        public int cd_busho { get; set; }
        public string nm_genryo { get; set; }
        public Nullable<decimal> tanka { get; set; }
        public Nullable<decimal> budomari { get; set; }
        public string nisugata { get; set; }
        public string kikakusho { get; set; }
        public Nullable<System.DateTime> dt_konyu { get; set; }
        public decimal id_toroku { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public decimal id_koshin { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public Nullable<short> flg_shiyo { get; set; }
        public Nullable<short> flg_mishiyo { get; set; }
        public byte[] ts { get; set; }
    }
}
