//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_genryo_seiho
    {
        public short cd_kaisha { get; set; }
        public short cd_kojyo { get; set; }
        public decimal cd_hin { get; set; }
        public byte kbn_hin { get; set; }
        public string nm_hin { get; set; }
        public string nm_hin_r { get; set; }
        public Nullable<double> nisugata_qty { get; set; }
        public string nisugata_hyoji { get; set; }
        public Nullable<int> su_iri { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<byte> cd_tani_nonyu { get; set; }
        public Nullable<byte> cd_tani_shiyo { get; set; }
        public string cd_shukei { get; set; }
        public Nullable<double> budomari { get; set; }
        public double hijyu { get; set; }
        public Nullable<short> cd_bunrui { get; set; }
        public Nullable<int> size_hachu { get; set; }
        public Nullable<int> su_leadtime { get; set; }
        public Nullable<double> su_saitei { get; set; }
        public string cd_kura { get; set; }
        public string nm_kura { get; set; }
        public Nullable<double> kin_tanka { get; set; }
        public Nullable<byte> kbn_zei { get; set; }
        public Nullable<byte> cd_hini { get; set; }
        public string nm_hini { get; set; }
        public string kbn_jyotai { get; set; }
        public string biko { get; set; }
        public string cd_niuke { get; set; }
        public string nm_niuke { get; set; }
        public string cd_maker_hin { get; set; }
        public Nullable<int> kikan_shomi { get; set; }
        public string tani_shomi { get; set; }
        public Nullable<int> kikan_shomi_kaifu { get; set; }
        public string tani_shomi_kaifu { get; set; }
        public string kbn_ksys_denso { get; set; }
        public Nullable<bool> flg_mishiyo { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<System.DateTime> dt_henko { get; set; }
        public Nullable<int> cd_koshin_kaisha { get; set; }
        public string cd_koshin { get; set; }
        public string cd_keiri_shukei { get; set; }
        public Nullable<byte> kbn_haishi { get; set; }
        public string kn_hin { get; set; }
        public string kn_nisugata { get; set; }
        public string cd_kamoku { get; set; }
        public string cd_genshi_bunrui { get; set; }
        public string no_kikaku { get; set; }
        public string nm_kikaku { get; set; }
        public Nullable<byte> cd_hini_gmat { get; set; }
        public string nm_bussitsu { get; set; }
        public Nullable<System.DateTime> dt_toroku_kikaku { get; set; }
        public Nullable<System.DateTime> dt_toroku_goody { get; set; }
        public Nullable<System.DateTime> dt_koshin_goody { get; set; }
        public string nm_seizo { get; set; }
        public string nm_hanbai { get; set; }
        public Nullable<bool> flg_fac_denso { get; set; }
        public Nullable<byte> kbn_hokan1 { get; set; }
        public Nullable<byte> kbn_hokan2 { get; set; }
        public Nullable<byte> kbn_hokan_goody { get; set; }
        public Nullable<decimal> cd_doto_hin { get; set; }
        public string cd_doto_kaisha { get; set; }
        public Nullable<System.DateTime> dt_doto_SET_DATE { get; set; }
    }
}
