//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_genryokojo_bf
    {
        public int cd_kaisha { get; set; }
        public int cd_busho { get; set; }
        public string cd_genryo { get; set; }
        public Nullable<decimal> wt_kayosei_kokeibutsu { get; set; }
        public Nullable<decimal> id_tanka_koshin { get; set; }
        public Nullable<System.DateTime> dt_tanka_koshin { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public byte[] ts { get; set; }
    }
}
