//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_haigo_meisai
    {
        public decimal cd_haigo { get; set; }
        public byte no_kotei { get; set; }
        public byte no_tonyu { get; set; }
        public decimal cd_hin { get; set; }
        public Nullable<bool> flg_shitei { get; set; }
        public byte kbn_hin { get; set; }
        public Nullable<byte> kbn_shikakari { get; set; }
        public string nm_hin { get; set; }
        public Nullable<int> cd_mark { get; set; }
        public Nullable<double> qty_haigo { get; set; }
        public Nullable<double> qty_nisugata { get; set; }
        public Nullable<decimal> gosa { get; set; }
        public Nullable<double> budomari { get; set; }
        public byte kbn_bunkatsu { get; set; }
    }
}
