//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_kengen
    {
        public short cd_kengen { get; set; }
        public string nm_kengen { get; set; }
        public decimal id_toroku { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public decimal id_koshin { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public short kbn_kengen_bunrui { get; set; }
        public Nullable<short> kbn_eigyo { get; set; }
        public byte[] ts { get; set; }
    }
}
