//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_kojyo
    {
        public short cd_kaisha { get; set; }
        public short cd_kojyo { get; set; }
        public string nm_kojyo { get; set; }
        public string str_prt_lit1 { get; set; }
        public string str_prt_lit2 { get; set; }
        public double ritsu_kihon { get; set; }
        public double budomari { get; set; }
        public int qty_kihon { get; set; }
        public double hijyu { get; set; }
        public byte kbn_hin { get; set; }
        public byte cd_setsubi { get; set; }
        public double qty_max { get; set; }
        public short cd_line { get; set; }
        public string nm_kigo { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<System.DateTime> dt_henko { get; set; }
        public byte kbn_nmacs_kojyo { get; set; }
        public byte su_linecode_standard { get; set; }
        public Nullable<short> cd_kojyo_old { get; set; }
    }
}
