//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_literal
    {
        public string cd_category { get; set; }
        public string cd_literal { get; set; }
        public string nm_literal { get; set; }
        public Nullable<int> value1 { get; set; }
        public Nullable<int> value2 { get; set; }
        public short no_sort { get; set; }
        public string biko { get; set; }
        public short flg_edit { get; set; }
        public Nullable<short> cd_group { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public string cd_2nd_literal { get; set; }
        public string nm_2nd_literal { get; set; }
        public Nullable<short> no_2nd_sort { get; set; }
        public Nullable<short> flg_2ndedit { get; set; }
        public string mail_address { get; set; }
        public string flg_mishiyo { get; set; }
        public byte[] ts { get; set; }
    }
}
