//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_line_togo
    {
        public int cd_kaisha { get; set; }
        public int cd_seizokojo { get; set; }
        public int cd_shokuba { get; set; }
        public int cd_line { get; set; }
        public string nm_line { get; set; }
        public Nullable<byte> cd_team { get; set; }
        public Nullable<bool> flg_shuka_2 { get; set; }
        public string kbn_kotei { get; set; }
        public Nullable<decimal> id_touroku { get; set; }
        public Nullable<System.DateTime> dt_touroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
    }
}
