//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_mark
    {
        public short cd_kaisha { get; set; }
        public short cd_kojyo { get; set; }
        public byte cd_mark { get; set; }
        public string nm_mark { get; set; }
        public string mark { get; set; }
        public byte cd_tani_shiyo { get; set; }
        public System.DateTime dt_henko { get; set; }
        public byte ss_kbn_qty_haigo { get; set; }
        public byte ss_kbn_nisugata { get; set; }
        public byte ss_kbn_gosa { get; set; }
        public byte ss_kbn_budomari { get; set; }
        public bool ss_flg_genryo { get; set; }
        public bool ss_flg_maeshori { get; set; }
        public bool ss_flg_shikakari { get; set; }
        public bool ss_flg_sagyo { get; set; }
    }
}
