//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_tab6_tokuseichi
    {
        public string no_seiho { get; set; }
        public short no_seq_seihintokuseichi { get; set; }
        public string nm_seihintokuseichi_combo_input { get; set; }
        public string kbn_seihintokuseichi { get; set; }
        public string nm_seihintokuseichi_ronrichi { get; set; }
        public string nm_seihintokuseichi_kenshisakuhin { get; set; }
        public string nm_seihintokuseichi_tp { get; set; }
        public string nm_seihintokuseichi_input1 { get; set; }
        public string nm_seihintokuseichi_input2 { get; set; }
        public string nm_seihintokuseichi_input3 { get; set; }
        public byte[] ts { get; set; }
    }
}
