//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_hyoshi
    {
        public string no_seiho { get; set; }
        public string no_hyojiyo_seiho { get; set; }
        public string cd_tokisaki { get; set; }
        public string cd_brand { get; set; }
        public string dt_seizo_kaishi_yotei { get; set; }
        public string nm_shozoku_group { get; set; }
        public string nm_shozoku_team { get; set; }
        public string nm_team_leader { get; set; }
        public string nm_juyo_gijitsu_joho { get; set; }
        public string nm_zenbankara_henkoten { get; set; }
        public string nm_seihin_tokucho { get; set; }
        public string nm_kyocho_hyoji { get; set; }
        public Nullable<System.DateTime> dt_create { get; set; }
        public string cd_create_shozoku_busho { get; set; }
        public string cd_create { get; set; }
        public Nullable<System.DateTime> dt_shonin1 { get; set; }
        public string cd_shonin1_shozoku_busho { get; set; }
        public string cd_shonin1 { get; set; }
        public Nullable<System.DateTime> dt_shonin2 { get; set; }
        public string cd_shonin2_shozoku_busho { get; set; }
        public string cd_shonin2 { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public string cd_toroku { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public string cd_koshin { get; set; }
        public byte[] ts { get; set; }
        public string nm_create_shozoku_busho { get; set; }
        public string nm_create { get; set; }
        public string nm_shonin1_shozoku_busho { get; set; }
        public string nm_shonin1 { get; set; }
        public string nm_shonin2_shozoku_busho { get; set; }
        public string nm_shonin2 { get; set; }
        public string shonin_memo { get; set; }
    }
}
