//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_tab7
    {
        public string no_seiho { get; set; }
        public string nm_free_kanren_tokkyo { get; set; }
        public string nm_free_tasha_kanren_tokkyo { get; set; }
        public string nm_shokuhin_tenkabutsu { get; set; }
        public string cd_eigyo_kyoka_gyoshu01 { get; set; }
        public string cd_eigyo_kyoka_gyoshu02 { get; set; }
        public string cd_eigyo_kyoka_gyoshu03 { get; set; }
        public string cd_eigyo_kyoka_gyoshu04 { get; set; }
        public string cd_eigyo_kyoka_gyoshu05 { get; set; }
        public string nm_free_genryo_shitei { get; set; }
        public string nm_free_genryo_seigen { get; set; }
        public string nm_free_sonota { get; set; }
        public byte[] ts { get; set; }
    }
}
