//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_tab6
    {
        public string no_seiho { get; set; }
        public Nullable<decimal> cd_shain { get; set; }
        public Nullable<decimal> no_oi { get; set; }
        public Nullable<decimal> nen { get; set; }
        public Nullable<short> seq_shisaku { get; set; }
        public string su_naiyoryo { get; set; }
        public Nullable<byte> cd_naiyoryo_tani { get; set; }
        public string nm_free_tokuseichi { get; set; }
        public string nm_free_biseibutsu { get; set; }
        public string kbn_shomikikan { get; set; }
        public string kbn_shomikikan_seizo_fukumu { get; set; }
        public string kbn_shomikikan_tani { get; set; }
        public Nullable<short> su_shomikikan_free_input { get; set; }
        public string kbn_meisho { get; set; }
        public string nm_meisho_hinmei { get; set; }
        public Nullable<double> su_nendo_sokuteichi { get; set; }
        public Nullable<System.DateTime> dt_nendo_sokuteichi { get; set; }
        public string nm_seihintokusechi_title1 { get; set; }
        public string nm_seihintokusechi_title2 { get; set; }
        public string nm_seihintokusechi_title3 { get; set; }
        public byte[] ts { get; set; }
    }
}
