//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_tab4
    {
        public string no_seiho { get; set; }
        public Nullable<decimal> su_haigo_suiso_g { get; set; }
        public Nullable<decimal> su_haigo_suiso_ml { get; set; }
        public Nullable<decimal> su_haigo_suiso_hiju { get; set; }
        public Nullable<decimal> su_haigo_yuso_g { get; set; }
        public Nullable<decimal> su_haigo_yuso_ml { get; set; }
        public Nullable<decimal> su_haigo_yuso_hiju { get; set; }
        public Nullable<decimal> su_haigo_gokei_g { get; set; }
        public Nullable<decimal> su_haigo_gokei_ml { get; set; }
        public Nullable<decimal> su_haigo_gokei_hiju { get; set; }
        public string nm_haigo_free_tokki_jiko { get; set; }
        public string nm_chuiten_free_komoku { get; set; }
        public byte[] ts { get; set; }
    }
}
