//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho
    {
        public string no_seiho { get; set; }
        public string nm_seiho { get; set; }
        public Nullable<System.DateTime> dt_seiho_sakusei { get; set; }
        public string nm_seiho_sakusei_1 { get; set; }
        public string nm_seiho_sakusei_2 { get; set; }
        public string nm_seiho_bunsho_before { get; set; }
        public Nullable<int> cd_shinsei_tanto_kaisha { get; set; }
        public string cd_shinsei_tanto { get; set; }
        public string nm_seiho_sekinin { get; set; }
        public Nullable<System.DateTime> dt_seiho_shinsei { get; set; }
        public Nullable<bool> flg_renewal { get; set; }
        public Nullable<decimal> cd_shain { get; set; }
        public Nullable<decimal> no_oi { get; set; }
        public Nullable<decimal> nen { get; set; }
        public Nullable<short> seq_shisaku { get; set; }
        public string nm_sample { get; set; }
    }
}
