//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_tab3
    {
        public string no_seiho { get; set; }
        public string nm_genryo_free_komoku { get; set; }
        public string nm_kiki_setsubi_free_komoku { get; set; }
        public string nm_seizo_hoso_free_komoku { get; set; }
        public string nm_hyoji_jiko_free_komoku { get; set; }
        public byte[] ts { get; set; }
    }
}
