//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_kakuninjiko
    {
        public string no_seiho { get; set; }
        public string nm_free_kanren_tokkyo { get; set; }
        public string nm_free_tasha_kanren_tokkyo { get; set; }
        public string nm_shokuhin_tenkabutsu { get; set; }
        public string nm_eigyo_kyoka_gyoshu01 { get; set; }
        public string nm_eigyo_kyoka_gyoshu02 { get; set; }
        public string nm_eigyo_kyoka_gyoshu03 { get; set; }
        public string nm_eigyo_kyoka_gyoshu04 { get; set; }
        public string nm_eigyo_kyoka_gyoshu05 { get; set; }
        public string nm_free_genryo_shitei { get; set; }
        public string nm_free_genryo_seigen { get; set; }
        public string nm_free_sonota { get; set; }
        public byte[] ts { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public string cd_toroku { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public string cd_koshin { get; set; }
    }
}
