//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_shomikigen
    {
        public string no_seiho { get; set; }
        public string nm_hozon_shiken_kankaku { get; set; }
        public string nm_hozon_shiken_kikan { get; set; }
        public string biko { get; set; }
        public string nm_shomikigen_biko { get; set; }
        public string nm_rikagaku_shiken_komoku { get; set; }
        public string nm_rikagaku_shiken_hinshitsu { get; set; }
        public string nm_rikagaku_shiken_kikan { get; set; }
        public string nm_rikagaku_shiken_hokoku { get; set; }
        public string nm_biseibutsu_shiken_komoku { get; set; }
        public string nm_biseibutsu_shiken_hinshitsu { get; set; }
        public string nm_biseibutsu_shiken_kikan { get; set; }
        public string nm_biseibutsu_shiken_hokoku { get; set; }
        public string nm_kanno_hyoka_komoku { get; set; }
        public string nm_kanno_hyoka_hinshitsu { get; set; }
        public string nm_kanno_hyoka_kikan { get; set; }
        public string nm_kanno_hyoka_hokoku { get; set; }
        public Nullable<decimal> no_anzen_keisu { get; set; }
        public string nm_kaihatsubusho { get; set; }
        public string nm_kaihatsutanto { get; set; }
        public byte[] ts { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public string cd_toroku { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public string cd_koshin { get; set; }
        public Nullable<short> cd_nengetsu_hyoji { get; set; }
    }
}
