//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_denso
    {
        public string no_seiho { get; set; }
        public short cd_kaisha { get; set; }
        public short cd_kojyo { get; set; }
        public bool flg_denso_taisho { get; set; }
        public bool flg_denso_jyotai { get; set; }
        public Nullable<System.DateTime> dt_denso_toroku { get; set; }
        public Nullable<System.DateTime> dt_denso_kanryo { get; set; }
        public bool flg_daihyo_kojyo { get; set; }
        public Nullable<int> cd_denso_tanto_kaisha { get; set; }
        public string cd_denso_tanto { get; set; }
        public string biko { get; set; }
        public byte[] ts { get; set; }
    }
}
