//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seizo_line
    {
        public decimal cd_haigo { get; set; }
        public int no_yusen { get; set; }
        public int cd_line { get; set; }
        public System.DateTime dt_henko { get; set; }
        public Nullable<int> cd_koshin_kaisha { get; set; }
        public string cd_koshin { get; set; }
    }
}
