//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_tokuseichi
    {
        public string no_seiho { get; set; }
        public short no_seq_seihintokusechi { get; set; }
        public string kbn_seihintokuseichi { get; set; }
        public string nm_seihintokusechi_combo_input { get; set; }
        public string nm_seihintokusechi_ronrichi { get; set; }
        public string nm_seihintokusechi_kenshisakuhin { get; set; }
        public string nm_seihintokusechi_tp { get; set; }
        public string nm_seihintokusechi_input1 { get; set; }
        public string nm_seihintokusechi_input2 { get; set; }
        public string nm_seihintokusechi_input3 { get; set; }
        public byte[] ts { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public string cd_toroku { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public string cd_koshin { get; set; }
    }
}
