//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_haigo_chui
    {
        public string no_seiho { get; set; }
        public Nullable<decimal> su_haigo_suiso_g { get; set; }
        public Nullable<decimal> su_haigo_suiso_ml { get; set; }
        public Nullable<decimal> su_haigo_suiso_hiju { get; set; }
        public Nullable<decimal> su_haigo_yuso_g { get; set; }
        public Nullable<decimal> su_haigo_yuso_ml { get; set; }
        public Nullable<decimal> su_haigo_yuso_hiju { get; set; }
        public Nullable<decimal> su_haigo_gokei_g { get; set; }
        public Nullable<decimal> su_haigo_gokei_ml { get; set; }
        public Nullable<decimal> su_haigo_gokei_hiju { get; set; }
        public string nm_haigo_free_tokki_jiko { get; set; }
        public string nm_chuiten_free_komoku { get; set; }
        public string pt_kotei { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public string cd_toroku { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public string cd_koshin { get; set; }
        public byte[] ts { get; set; }
    }
}
