//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seiho_bunsho_seihinkikaku
    {
        public string no_seiho { get; set; }
        public string su_naiyoryo { get; set; }
        public Nullable<byte> cd_naiyoryo_tani { get; set; }
        public string nm_free_tokuseichi { get; set; }
        public string nm_free_biseibutsu { get; set; }
        public string kbn_shomikikan { get; set; }
        public string kbn_shomikikan_seizo_fukumu { get; set; }
        public Nullable<short> su_shomikikan_free_input { get; set; }
        public string kbn_shomikikan_tani { get; set; }
        public string kbn_toriatsukai_ondo { get; set; }
        public string kbn_meisho { get; set; }
        public string nm_meisho_hinmei { get; set; }
        public Nullable<decimal> su_nendo_sokuteichi { get; set; }
        public string dt_nendo_sokuteichi { get; set; }
        public string nm_seihintokusechi_title1 { get; set; }
        public string nm_seihintokusechi_title2 { get; set; }
        public string nm_seihintokusechi_title3 { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public string cd_toroku { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public string cd_koshin { get; set; }
        public byte[] ts { get; set; }
    }
}
