//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_seihin_seiho
    {
        public decimal cd_hin { get; set; }
        public string nm_seihin { get; set; }
        public string nisugata_hyoji { get; set; }
        public Nullable<int> no_yusen { get; set; }
        public Nullable<decimal> cd_haigo { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<System.DateTime> dt_henko { get; set; }
        public Nullable<int> cd_koshin_kaisha { get; set; }
        public string cd_koshin { get; set; }
        public Nullable<System.DateTime> dt_henko_goody { get; set; }
        public byte[] ts { get; set; }
    }
}
