//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_team
    {
        public short cd_group { get; set; }
        public short cd_team { get; set; }
        public string nm_team { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<short> flg_hyoji { get; set; }
        public byte[] ts { get; set; }
    }
}
