//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_user_new
    {
        public decimal id_user { get; set; }
        public string password { get; set; }
        public Nullable<short> cd_kengen { get; set; }
        public string nm_user { get; set; }
        public int cd_kaisha { get; set; }
        public int cd_busho { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<short> cd_group { get; set; }
        public Nullable<short> cd_team { get; set; }
        public string cd_yakushoku { get; set; }
    }
}
