//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_user
    {
        public decimal id_user { get; set; }
        public string password { get; set; }
        public short cd_kengen { get; set; }
        public string nm_user { get; set; }
        public int cd_kaisha { get; set; }
        public Nullable<int> cd_busho { get; set; }
        public Nullable<short> cd_group { get; set; }
        public Nullable<short> cd_team { get; set; }
        public string cd_yakushoku { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<decimal> id_josi { get; set; }
        public Nullable<System.DateTime> dt_password { get; set; }
    }
}
