//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_yoki_hoso_shizai
    {
        public short cd_yoki_hoso_shizai { get; set; }
        public string nm_yoki_hoso_shizai { get; set; }
        public Nullable<short> cd_maker01 { get; set; }
        public Nullable<short> cd_maker02 { get; set; }
        public Nullable<short> cd_maker03 { get; set; }
        public Nullable<short> cd_maker04 { get; set; }
        public Nullable<short> cd_maker05 { get; set; }
        public Nullable<decimal> no_shizai_kikakusho01 { get; set; }
        public Nullable<decimal> no_shizai_kikakusho02 { get; set; }
        public Nullable<decimal> no_shizai_kikakusho03 { get; set; }
        public Nullable<decimal> no_shizai_kikakusho04 { get; set; }
        public Nullable<decimal> no_shizai_kikakusho05 { get; set; }
        public Nullable<short> cd_zaishitsu01 { get; set; }
        public Nullable<short> cd_zaishitsu02 { get; set; }
        public Nullable<short> cd_zaishitsu03 { get; set; }
        public Nullable<short> cd_zaishitsu04 { get; set; }
        public Nullable<short> cd_zaishitsu05 { get; set; }
        public Nullable<short> cd_recycle_hyoji01 { get; set; }
        public Nullable<short> cd_recycle_hyoji02 { get; set; }
        public Nullable<short> cd_recycle_hyoji03 { get; set; }
        public Nullable<short> cd_recycle_hyoji04 { get; set; }
        public Nullable<short> cd_recycle_hyoji05 { get; set; }
        public string nm_size01 { get; set; }
        public string nm_size02 { get; set; }
        public string nm_size03 { get; set; }
        public string nm_size04 { get; set; }
        public string nm_size05 { get; set; }
        public string nm_free_komoku { get; set; }
        public byte[] ts { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public string cd_toroku { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public string cd_koshin { get; set; }
    }
}
