//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_yoki_hoso
    {
        public int cd_yoki_hoso { get; set; }
        public string nm_yoki_hoso { get; set; }
        public Nullable<short> cd_yoki_hoso_shizai01 { get; set; }
        public Nullable<short> cd_yoki_hoso_shizai02 { get; set; }
        public Nullable<short> cd_yoki_hoso_shizai03 { get; set; }
        public Nullable<short> cd_yoki_hoso_shizai04 { get; set; }
        public Nullable<short> cd_yoki_hoso_shizai05 { get; set; }
        public Nullable<short> cd_yoki_hoso_shizai06 { get; set; }
        public Nullable<short> cd_yoki_hoso_shizai07 { get; set; }
        public Nullable<short> cd_yoki_hoso_shizai08 { get; set; }
        public Nullable<short> cd_yoki_hoso_shizai09 { get; set; }
        public Nullable<short> cd_yoki_hoso_shizai10 { get; set; }
        public byte[] ts { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public string cd_toroku { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public string cd_koshin { get; set; }
    }
}
