//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_change_log
    {
        public int no_rireki { get; set; }
        public Nullable<int> id_function { get; set; }
        public string nm_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public byte[] ts { get; set; }
    }
}
