//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_event_log
    {
        public string no_seiho { get; set; }
        public int cd_tanto_kaisha { get; set; }
        public string cd_tanto { get; set; }
        public string cd_koshin { get; set; }
        public string nm_shori { get; set; }
        public string nm_ope { get; set; }
        public System.DateTime dt_shori { get; set; }
        public string ip_address { get; set; }
        public byte kbn_system { get; set; }
    }
}
