//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_gate_header
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public string nm_sample_plan { get; set; }
        public Nullable<bool> flg_shonin_tanto_plan { get; set; }
        public string nm_shonin_tanto_plan { get; set; }
        public Nullable<System.DateTime> dt_shonin_tanto_plan { get; set; }
        public Nullable<bool> flg_shonin_reader_plan { get; set; }
        public string nm_shonin_reader_plan { get; set; }
        public Nullable<System.DateTime> dt_shonin_reader_plan { get; set; }
        public string nm_sample_confirm { get; set; }
        public Nullable<bool> flg_shonin_tanto_confirm { get; set; }
        public string nm_shonin_tanto_confirm { get; set; }
        public Nullable<System.DateTime> dt_shonin_tanto_confirm { get; set; }
        public Nullable<bool> flg_shonin_reader_confirm { get; set; }
        public string nm_shonin_reader_confirm { get; set; }
        public Nullable<System.DateTime> dt_shonin_reader_confirm { get; set; }
        public string nm_comment_tanto { get; set; }
        public string nm_comment_reader { get; set; }
        public Nullable<decimal> kbn_haita { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public byte[] ts { get; set; }
    }
}
