//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_genryo
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public short seq_shisaku { get; set; }
        public Nullable<short> flg_print { get; set; }
        public string zyusui { get; set; }
        public string zyuabura { get; set; }
        public string gokei { get; set; }
        public string genryohi { get; set; }
        public string genryohi1 { get; set; }
        public string hiju { get; set; }
        public string yoryo { get; set; }
        public string irisu { get; set; }
        public string yukobudomari { get; set; }
        public string reberu { get; set; }
        public string hizyubudomari { get; set; }
        public string heikinzyu { get; set; }
        public string cs_genryo { get; set; }
        public string cs_zairyohi { get; set; }
        public string cs_keihi { get; set; }
        public string cs_genka { get; set; }
        public string ko_genka { get; set; }
        public string ko_baika { get; set; }
        public string ko_riritu { get; set; }
        public decimal id_toroku { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public decimal id_koshin { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public byte[] ts { get; set; }
    }
}
