//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_gate_meisai
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public int no_gate { get; set; }
        public int no_bunrui { get; set; }
        public int no_check { get; set; }
        public int no_meisai { get; set; }
        public Nullable<int> no_sort { get; set; }
        public Nullable<bool> flg_check_plan { get; set; }
        public Nullable<bool> flg_check_review { get; set; }
        public string nm_check_bunrui { get; set; }
        public string nm_check { get; set; }
        public string col_item { get; set; }
        public Nullable<bool> flg_check { get; set; }
        public string nm_check_note1 { get; set; }
        public string col_note1 { get; set; }
        public Nullable<bool> flg_check_note1 { get; set; }
        public string nm_check_note2 { get; set; }
        public string col_note2 { get; set; }
        public Nullable<bool> flg_check_note2 { get; set; }
        public string nm_comment_plan { get; set; }
        public string col_comment_plan { get; set; }
        public string nm_comment_confirm { get; set; }
        public string col_comment_confirm { get; set; }
        public string nm_free { get; set; }
        public string col_free { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public byte[] ts { get; set; }
    }
}
