//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_haigo
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public short cd_kotei { get; set; }
        public short seq_kotei { get; set; }
        public string nm_kotei { get; set; }
        public string zoku_kotei { get; set; }
        public Nullable<short> sort_kotei { get; set; }
        public Nullable<short> sort_genryo { get; set; }
        public string cd_genryo { get; set; }
        public Nullable<int> cd_kaisha { get; set; }
        public Nullable<int> cd_busho { get; set; }
        public string nm_genryo { get; set; }
        public Nullable<decimal> tanka { get; set; }
        public Nullable<decimal> budomari { get; set; }
        public Nullable<decimal> ritu_abura { get; set; }
        public Nullable<decimal> ritu_sakusan { get; set; }
        public Nullable<decimal> ritu_shokuen { get; set; }
        public Nullable<decimal> ritu_sousan { get; set; }
        public string color { get; set; }
        public decimal id_toroku { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public decimal id_koshin { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public Nullable<decimal> ritu_msg { get; set; }
        public byte[] ts { get; set; }
    }
}
