//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_ikkatsu_output
    {
        public decimal no_ikkatsu { get; set; }
        public string no_seiho { get; set; }
        public byte flg_seihobunsho { get; set; }
        public byte flg_haigosakusei { get; set; }
        public System.DateTime dt_from { get; set; }
        public System.DateTime dt_to { get; set; }
        public byte flg_01 { get; set; }
        public byte flg_19 { get; set; }
        public byte flg_20 { get; set; }
        public byte flg_21 { get; set; }
        public byte flg_denso { get; set; }
        public byte flg_kakunin { get; set; }
        public byte kbn_kaihatsu_kaisha { get; set; }
        public string memo { get; set; }
        public byte status { get; set; }
        public System.DateTime dt_seiho_sakusei { get; set; }
        public System.DateTime dt_denso_toroku { get; set; }
        public Nullable<System.DateTime> dt_denso_kanryo { get; set; }
        public byte flg_seihobunsho_output { get; set; }
        public byte flg_haigosakusei_output { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public int cd_toroku_kaisha { get; set; }
        public string cd_toroku { get; set; }
    }
}
