//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_shisaku_list_bf
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public short seq_shisaku { get; set; }
        public short cd_kotei { get; set; }
        public short seq_kotei { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> quantity_kanzan { get; set; }
        public string color { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<decimal> juryo_shiagari_seq { get; set; }
        public byte[] ts { get; set; }
    }
}
