//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_shisaku_bf
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public short seq_shisaku { get; set; }
        public Nullable<short> sort_shisaku { get; set; }
        public Nullable<short> no_chui { get; set; }
        public string nm_sample { get; set; }
        public string memo { get; set; }
        public Nullable<short> flg_print { get; set; }
        public string no_seiho1 { get; set; }
        public string no_seiho2 { get; set; }
        public string no_seiho3 { get; set; }
        public string no_seiho4 { get; set; }
        public string no_seiho5 { get; set; }
        public Nullable<decimal> su_fc { get; set; }
        public Nullable<decimal> su_brix { get; set; }
        public Nullable<decimal> su_ph { get; set; }
        public Nullable<decimal> su_ca { get; set; }
        public string ph { get; set; }
        public Nullable<short> flg_ph { get; set; }
        public Nullable<decimal> Brix { get; set; }
        public Nullable<short> flg_Brix { get; set; }
        public Nullable<decimal> CA { get; set; }
        public Nullable<short> flg_CA { get; set; }
        public string memo_sakusei { get; set; }
        public Nullable<short> flg_memo { get; set; }
        public string hyoka { get; set; }
        public Nullable<short> flg_hyoka { get; set; }
        public Nullable<System.DateTime> dt_shisaku { get; set; }
        public Nullable<decimal> juryo_shiagari_g { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public string siki_keisan { get; set; }
        public string free_title1 { get; set; }
        public string free_value1 { get; set; }
        public Nullable<short> flg_free1 { get; set; }
        public string free_title2 { get; set; }
        public string free_value2 { get; set; }
        public Nullable<short> flg_free2 { get; set; }
        public string free_title3 { get; set; }
        public string free_value3 { get; set; }
        public Nullable<short> flg_free3 { get; set; }
        public string free_title4 { get; set; }
        public string free_value4 { get; set; }
        public Nullable<short> flg_free4 { get; set; }
        public string free_title5 { get; set; }
        public string free_value5 { get; set; }
        public Nullable<short> flg_free5 { get; set; }
        public string free_title6 { get; set; }
        public string free_value6 { get; set; }
        public Nullable<short> flg_free6 { get; set; }
        public string free_title7 { get; set; }
        public string free_value7 { get; set; }
        public Nullable<short> flg_free7 { get; set; }
        public string free_title8 { get; set; }
        public string free_value8 { get; set; }
        public Nullable<short> flg_free8 { get; set; }
        public string free_title9 { get; set; }
        public string free_value9 { get; set; }
        public Nullable<short> flg_free9 { get; set; }
        public string free_title10 { get; set; }
        public string free_value10 { get; set; }
        public Nullable<short> flg_free10 { get; set; }
        public string free_title11 { get; set; }
        public string free_value11 { get; set; }
        public Nullable<short> flg_free11 { get; set; }
        public string free_title12 { get; set; }
        public string free_value12 { get; set; }
        public Nullable<short> flg_free12 { get; set; }
        public string free_title13 { get; set; }
        public string free_value13 { get; set; }
        public Nullable<short> flg_free13 { get; set; }
        public string free_title14 { get; set; }
        public string free_value14 { get; set; }
        public Nullable<short> flg_free14 { get; set; }
        public string free_title15 { get; set; }
        public string free_value15 { get; set; }
        public Nullable<short> flg_free15 { get; set; }
        public string free_title16 { get; set; }
        public string free_value16 { get; set; }
        public Nullable<short> flg_free16 { get; set; }
        public string free_title17 { get; set; }
        public string free_value17 { get; set; }
        public Nullable<short> flg_free17 { get; set; }
        public string free_title18 { get; set; }
        public string free_value18 { get; set; }
        public Nullable<short> flg_free18 { get; set; }
        public string free_title19 { get; set; }
        public string free_value19 { get; set; }
        public Nullable<short> flg_free19 { get; set; }
        public string free_title20 { get; set; }
        public string free_value20 { get; set; }
        public Nullable<short> flg_free20 { get; set; }
        public Nullable<decimal> kg_costrecipe { get; set; }
        public Nullable<decimal> ko_costrecipe { get; set; }
        public byte[] ts { get; set; }
    }
}
