//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_shisan_shizai
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public short seq_shizai { get; set; }
        public decimal no_eda { get; set; }
        public Nullable<short> no_sort { get; set; }
        public Nullable<int> cd_kaisha { get; set; }
        public Nullable<int> cd_busho_ { get; set; }
        public string cd_shizai { get; set; }
        public string nm_shizai { get; set; }
        public Nullable<decimal> tanka { get; set; }
        public Nullable<decimal> budomari { get; set; }
        public Nullable<decimal> cs_siyou { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public string cd_shizai_new { get; set; }
        public string nm_shizai_new { get; set; }
        public Nullable<int> cd_seizokojo { get; set; }
        public Nullable<int> cd_shokuba { get; set; }
        public Nullable<int> cd_line { get; set; }
        public string cd_seihin { get; set; }
        public string cd_taisyoshizai { get; set; }
        public Nullable<int> cd_hattyusaki { get; set; }
        public Nullable<int> chk_kanryo { get; set; }
        public Nullable<decimal> cd_hattyu { get; set; }
        public Nullable<System.DateTime> dt_hattyu { get; set; }
        public string nm_file_henshita { get; set; }
        public string file_path_henshita { get; set; }
    }
}
