//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_shisakuhin
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public string no_irai { get; set; }
        public string nm_hin { get; set; }
        public Nullable<int> cd_kaisha { get; set; }
        public Nullable<int> cd_kojo { get; set; }
        public string cd_shubetu { get; set; }
        public Nullable<int> no_shubetu { get; set; }
        public Nullable<short> cd_group { get; set; }
        public Nullable<short> cd_team { get; set; }
        public string cd_ikatu { get; set; }
        public string cd_genre { get; set; }
        public string cd_user { get; set; }
        public string tokuchogenryo { get; set; }
        public string youto { get; set; }
        public string cd_kakaku { get; set; }
        public Nullable<decimal> cd_eigyo { get; set; }
        public string cd_hoho { get; set; }
        public string cd_juten { get; set; }
        public string hoho_sakin { get; set; }
        public string youki { get; set; }
        public string yoryo { get; set; }
        public string cd_tani { get; set; }
        public string su_iri { get; set; }
        public string cd_ondo { get; set; }
        public string shomikikan { get; set; }
        public string genka { get; set; }
        public string baika { get; set; }
        public string buturyo { get; set; }
        public string dt_hatubai { get; set; }
        public string uriage_k { get; set; }
        public string rieki_k { get; set; }
        public string uriage_h { get; set; }
        public string rieki_h { get; set; }
        public string cd_nisugata { get; set; }
        public string memo { get; set; }
        public Nullable<short> keta_shosu { get; set; }
        public Nullable<short> kbn_haishi { get; set; }
        public Nullable<decimal> kbn_haita { get; set; }
        public Nullable<short> seq_shisaku { get; set; }
        public string memo_shisaku { get; set; }
        public Nullable<short> flg_chui { get; set; }
        public decimal id_toroku { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public decimal id_koshin { get; set; }
        public System.DateTime dt_koshin { get; set; }
        public string pt_kotei { get; set; }
        public Nullable<short> flg_secret { get; set; }
        public Nullable<int> cd_hanseki { get; set; }
        public byte[] ts { get; set; }
        public string shomikikan_tani { get; set; }
        public string no_seiho_copy { get; set; }
    }
}
