//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_shisan_shisakuhin
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public decimal no_eda { get; set; }
        public Nullable<int> cd_kaisha { get; set; }
        public Nullable<int> cd_kojo { get; set; }
        public string su_iri { get; set; }
        public string genka { get; set; }
        public string baika { get; set; }
        public string cd_genka_tani { get; set; }
        public string buturyo { get; set; }
        public string dt_hatubai { get; set; }
        public string uriage_k { get; set; }
        public string rieki_k { get; set; }
        public string uriage_h { get; set; }
        public string rieki_h { get; set; }
        public string cd_nisugata { get; set; }
        public string lot { get; set; }
        public Nullable<int> saiyo_sample { get; set; }
        public Nullable<decimal> ken_id_koshin { get; set; }
        public Nullable<System.DateTime> ken_dt_koshin { get; set; }
        public Nullable<decimal> sei_id_koshin { get; set; }
        public Nullable<System.DateTime> sei_dt_koshin { get; set; }
        public Nullable<decimal> gen_id_koshin { get; set; }
        public Nullable<System.DateTime> gen_dt_koshin { get; set; }
        public Nullable<decimal> kojo_id_koshin { get; set; }
        public Nullable<System.DateTime> kojo_dt_koshin { get; set; }
        public Nullable<System.DateTime> sam_dt_koshin { get; set; }
        public Nullable<short> fg_keisan { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<decimal> sam_id_koshin { get; set; }
        public Nullable<decimal> haita_id_user { get; set; }
        public string kikan_hanbai_sen { get; set; }
        public string kikan_hanbai_tani { get; set; }
        public string shurui_eda { get; set; }
        public string yoryo { get; set; }
        public Nullable<System.DateTime> dt_kizitu { get; set; }
        public Nullable<int> su_irai { get; set; }
        public Nullable<int> kikan_hanbai_suti { get; set; }
        public string nm_edaShisaku { get; set; }
        public Nullable<int> cd_hanseki { get; set; }
        public byte[] ts { get; set; }
    }
}
