//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_shisan_kihonjoho
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public short seq_shisaku { get; set; }
        public decimal no_eda { get; set; }
        public string genka { get; set; }
        public string baika { get; set; }
        public string cd_genka_tani { get; set; }
        public string buturyo { get; set; }
        public string dt_hatubai { get; set; }
        public string kikan_hanbai_sen { get; set; }
        public Nullable<int> kikan_hanbai_suti { get; set; }
        public string kikan_hanbai_tani { get; set; }
        public string uriage_k { get; set; }
        public string rieki_k { get; set; }
        public string lot { get; set; }
        public string uriage_h { get; set; }
        public string rieki_h { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<decimal> buturyo_suti { get; set; }
        public Nullable<short> buturyo_seihin { get; set; }
        public Nullable<short> buturyo_kikan { get; set; }
    }
}
