//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_shisan_status_rireki
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public decimal no_eda { get; set; }
        public System.DateTime dt_henkou { get; set; }
        public Nullable<int> cd_kaisha { get; set; }
        public Nullable<int> cd_busho { get; set; }
        public Nullable<decimal> id_henkou { get; set; }
        public string cd_zikko_ca { get; set; }
        public string cd_zikko_li { get; set; }
        public Nullable<int> st_kenkyu { get; set; }
        public Nullable<int> st_seisan { get; set; }
        public Nullable<int> st_gensizai { get; set; }
        public Nullable<int> st_kojo { get; set; }
        public Nullable<int> st_eigyo { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
    }
}
