//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_shisan_shisaku
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public short seq_shisaku { get; set; }
        public decimal no_eda { get; set; }
        public Nullable<decimal> juryo_shiagari_g { get; set; }
        public Nullable<System.DateTime> dt_shisan { get; set; }
        public Nullable<decimal> budomari { get; set; }
        public Nullable<decimal> heikinjuten { get; set; }
        public Nullable<decimal> cs_kotei { get; set; }
        public Nullable<decimal> kg_kotei { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<short> fg_chusi { get; set; }
        public Nullable<short> fg_koumokuchk { get; set; }
        public Nullable<decimal> cs_rieki { get; set; }
        public Nullable<decimal> kg_rieki { get; set; }
        public byte[] ts { get; set; }
    }
}
