//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_shisan_haigo
    {
        public decimal cd_shain { get; set; }
        public decimal nen { get; set; }
        public decimal no_oi { get; set; }
        public short cd_kotei { get; set; }
        public short seq_kotei { get; set; }
        public decimal no_eda { get; set; }
        public string nm_genryo { get; set; }
        public Nullable<decimal> tanka_ins { get; set; }
        public Nullable<decimal> budomari_ins { get; set; }
        public Nullable<decimal> tanka_ma { get; set; }
        public Nullable<decimal> budomar_ma { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<int> cd_kaisha_tanka { get; set; }
        public Nullable<int> cd_kojo_tanka { get; set; }
        public Nullable<int> cd_kaisha_budomari { get; set; }
        public Nullable<int> cd_kojo_budomari { get; set; }
    }
}
