//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_tenpu_bunsho
    {
        public string no_seiho { get; set; }
        public string nm_file { get; set; }
        public string setsumei { get; set; }
        public string nm_toroku { get; set; }
        public Nullable<int> cd_toroku_kaisha { get; set; }
        public string cd_toroku { get; set; }
        public Nullable<System.DateTime> dt_henko { get; set; }
        public byte[] ts { get; set; }
    }
}
