//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_kaisha_kojyo
    {
        public short cd_kaisha { get; set; }
        public string nm_kaisha { get; set; }
        public short cd_kojyo { get; set; }
        public string nm_kojyo { get; set; }
        public int qty_kihon { get; set; }
        public int su_code_standard { get; set; }
        public byte kbn_nmacs_kojyo { get; set; }
    }
}
