//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ma_seihin
    {
        public int cd_kaisha_seihin { get; set; }
        public int cd_busho_seihin { get; set; }
        public decimal cd_seihin { get; set; }
        public decimal cd_shizai { get; set; }
        public string nm_shizai { get; set; }
        public Nullable<decimal> tanka { get; set; }
        public Nullable<decimal> budomari { get; set; }
        public Nullable<decimal> siyoryo { get; set; }
        public Nullable<short> fg_seihin { get; set; }
        public string nm_seihin { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
    }
}
