//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ma_gate_check
    {
        public int no_gate { get; set; }
        public int no_bunrui { get; set; }
        public int no_check { get; set; }
        public Nullable<int> no_sort { get; set; }
        public Nullable<int> kbn_disp { get; set; }
        public Nullable<bool> flg_check_disp { get; set; }
        public string nm_check_bunrui { get; set; }
        public string nm_check { get; set; }
        public string nm_check_note1 { get; set; }
        public string nm_check_note2 { get; set; }
        public Nullable<System.DateTime> dt_toroku { get; set; }
        public Nullable<decimal> id_toroku { get; set; }
        public Nullable<System.DateTime> dt_koshin { get; set; }
        public Nullable<decimal> id_koshin { get; set; }
        public string nm_bunrui { get; set; }
        public Nullable<decimal> cd_shain { get; set; }
        public Nullable<decimal> nen { get; set; }
        public Nullable<decimal> no_oi { get; set; }
        public Nullable<int> no_meisai { get; set; }
    }
}
