//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_no_seiho_shurui
    {
        public string cd_hin_syurui { get; set; }
        public string cd_literal { get; set; }
        public string no_seiho_shurui { get; set; }
        public string nm_hin_syurui { get; set; }
        public Nullable<short> no_sort { get; set; }
    }
}
