//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_shohinkaihatsu_ikkatsuShutsuryoToroku_206
    {
        public decimal no_ikkatsu { get; set; }
        public System.DateTime dt_toroku { get; set; }
        public byte flg_denso { get; set; }
        public byte flg_kakunin { get; set; }
        public System.DateTime dt_from { get; set; }
        public System.DateTime dt_to { get; set; }
        public string memo { get; set; }
        public byte flg_01 { get; set; }
        public byte flg_19 { get; set; }
        public byte flg_20 { get; set; }
        public byte flg_21 { get; set; }
        public string nm_user { get; set; }
    }
}
