//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_shohinkaihatsu_tantokaisha_get_ZenkojoTankaBudomari
    {
        public decimal id_user { get; set; }
        public int cd_tantokaisha { get; set; }
        public short cd_kaisha { get; set; }
        public string nm_kaisha { get; set; }
        public string cd_category { get; set; }
        public string nm_literal { get; set; }
        public Nullable<int> value1 { get; set; }
    }
}
