//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_shohinkaihatsu_log_operation
    {
        public int no_seq { get; set; }
        public string cd_taisho_data { get; set; }
        public string nm_mode { get; set; }
        public string cd_tanto { get; set; }
        public string nm_user { get; set; }
        public Nullable<int> cd_tanto_kaisha { get; set; }
        public string nm_kaisha { get; set; }
        public string cd_gamen { get; set; }
        public string nm_literal { get; set; }
        public Nullable<System.DateTimeOffset> dt_operation { get; set; }
        public Nullable<System.DateTime> d_operation { get; set; }
        public Nullable<short> no_sort { get; set; }
    }
}
