//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_shohinkaihatsu_dialog_g3_nm_meisho_hinmei
    {
        public string KEN1_HINNM_C { get; set; }
        public string KEN1_HINNM_NM { get; set; }
    }
}
