/** 最終更新日 : 2016-10-17 **/
//------------------------------------------------------------------------------
// <auto-generated>
//    縺薙・繧ｳ繝ｼ繝峨・繝・Φ繝励Ξ繝ｼ繝医°繧臥函謌舌＆繧後∪縺励◆縲・
//
//    縺薙・繝輔ぃ繧､繝ｫ繧呈焔蜍輔〒螟画峩縺吶ｋ縺ｨ縲√い繝励Μ繧ｱ繝ｼ繧ｷ繝ｧ繝ｳ縺ｧ莠域悄縺励↑縺・虚菴懊′逋ｺ逕溘☆繧句庄閭ｽ諤ｧ縺後≠繧翫∪縺吶・
//    縺薙・繝輔ぃ繧､繝ｫ縺ｫ蟇ｾ縺吶ｋ謇句虚縺ｮ螟画峩縺ｯ縲√さ繝ｼ繝峨′蜀咲函謌舌＆繧後ｋ縺ｨ荳頑嶌縺阪＆繧後∪縺吶・
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_shain_info
    {
        public decimal cd_shain { get; set; }
        public string nm_shain { get; set; }
        public decimal cd_shozoku { get; set; }
        public decimal cd_shozoku_oi { get; set; }
        public string nm_shozoku { get; set; }
        public Nullable<decimal> cd_kaisha { get; set; }
        public string nm_kaisha { get; set; }
        public int cd_system { get; set; }
        public int type_kengen { get; set; }
        public int cd_kengen { get; set; }
    }
}
