//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_user_info
    {
        public decimal id_user { get; set; }
        public string nm_user { get; set; }
        public short cd_kengen { get; set; }
        public Nullable<short> kbn_kengen_bunrui { get; set; }
        public int cd_kaisha { get; set; }
        public string nm_kaisha { get; set; }
        public Nullable<int> cd_busho { get; set; }
        public string nm_busho { get; set; }
        public short cd_group { get; set; }
        public string nm_group { get; set; }
        public short cd_team { get; set; }
        public string nm_team { get; set; }
        public string cd_literal { get; set; }
        public string nm_literal { get; set; }
        public bool flg_kaishakan_sansyo { get; set; }
        public bool flg_kojyokan_sansyo { get; set; }
        public byte su_linecode_standard { get; set; }
        public Nullable<int> su_code_standard { get; set; }
    }
}
