//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_user_gamen_info
    {
        public short id_gamen { get; set; }
        public short id_kino { get; set; }
        public short id_data { get; set; }
        public decimal id_user { get; set; }
        public int cd_kaisha { get; set; }
    }
}
