//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_yoki_hoso_shizai
    {
        public long no_seq { get; set; }
        public short cd_yoki_hoso_shizai { get; set; }
        public string nm_yoki_hoso_shizai { get; set; }
    }
}
