//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wk_shisaku_genryo_delivery_bf
    {
        public int id_session { get; set; }
        public int cd_kaisha { get; set; }
        public int cd_kojo { get; set; }
        public short sort_kotei { get; set; }
        public short sort_genryo { get; set; }
        public string cd_genryo { get; set; }
        public string nm_genryo { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public System.DateTime dt_toroku { get; set; }
    }
}
