//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wk_shisaku_genryo_delivery
    {
        public int id_session { get; set; }
        public int cd_kaisha { get; set; }
        public int cd_kojo { get; set; }
        public short sort_kotei { get; set; }
        public short sort_genryo { get; set; }
        public string cd_genryo { get; set; }
        public string nm_genryo { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public System.DateTime dt_toroku { get; set; }
    }
}
